2025-03-04 13:43:44,298 - main - INFO - 환경변수 및 설정 초기화 중...
2025-03-04 13:43:44,300 - main - INFO - Bybit 테스트넷 클라이언트 초기화 중...
2025-03-04 13:43:44,311 - main - INFO - 서비스 초기화 중...
2025-03-04 13:43:44,311 - main - INFO - 마켓 데이터 서비스 중...
2025-03-04 13:43:46,006 - services.market_data_service - INFO - 마켓 데이터 로드 완료
2025-03-04 13:43:48,419 - telegram_bot.bot - INFO - 텔레그램 설정 로드:
2025-03-04 13:43:48,432 - telegram_bot.bot - INFO - - admin_chat_id: 583881676
2025-03-04 13:43:48,432 - telegram_bot.bot - INFO - - alert_chat_ids: [-1002464784986]
2025-03-04 13:43:48,857 - apscheduler.scheduler - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2025-03-04 13:43:48,857 - telegram_bot.bot - INFO - 봇 초기화 시작...
2025-03-04 13:43:48,857 - services.trade_history_service - INFO - === 포지션 정보 초기화 시작 ===
2025-03-04 13:43:48,860 - services.trade_history_service - INFO - 조회 기간: 2024-12-04 ~ 2025-03-04
2025-03-04 13:43:48,860 - services.trade_store - INFO - 날짜 범위 조회: 20241204 ~ 20250304
2025-03-04 13:43:48,860 - services.trade_store - INFO - 날짜: 20241204, 포지션 수: 0건
2025-03-04 13:43:48,860 - services.trade_store - INFO - 날짜: 20241205, 포지션 수: 0건
2025-03-04 13:43:48,860 - services.trade_store - INFO - 날짜: 20241206, 포지션 수: 0건
2025-03-04 13:43:48,860 - services.trade_store - INFO - 날짜: 20241207, 포지션 수: 0건
2025-03-04 13:43:48,860 - services.trade_store - INFO - 날짜: 20241208, 포지션 수: 0건
2025-03-04 13:43:48,860 - services.trade_store - INFO - 날짜: 20241209, 포지션 수: 0건
2025-03-04 13:43:48,860 - services.trade_store - INFO - 날짜: 20241210, 포지션 수: 0건
2025-03-04 13:43:48,860 - services.trade_store - INFO - 날짜: 20241211, 포지션 수: 0건
2025-03-04 13:43:48,860 - services.trade_store - INFO - 날짜: 20241212, 포지션 수: 0건
2025-03-04 13:43:48,860 - services.trade_store - INFO - 날짜: 20241213, 포지션 수: 0건
2025-03-04 13:43:48,860 - services.trade_store - INFO - 날짜: 20241214, 포지션 수: 0건
2025-03-04 13:43:48,860 - services.trade_store - INFO - 날짜: 20241215, 포지션 수: 0건
2025-03-04 13:43:48,860 - services.trade_store - INFO - 날짜: 20241216, 포지션 수: 0건
2025-03-04 13:43:48,860 - services.trade_store - INFO - 날짜: 20241217, 포지션 수: 0건
2025-03-04 13:43:48,860 - services.trade_store - INFO - 날짜: 20241218, 포지션 수: 0건
2025-03-04 13:43:48,860 - services.trade_store - INFO - 날짜: 20241219, 포지션 수: 0건
2025-03-04 13:43:48,860 - services.trade_store - INFO - 날짜: 20241220, 포지션 수: 0건
2025-03-04 13:43:48,860 - services.trade_store - INFO - 날짜: 20241221, 포지션 수: 0건
2025-03-04 13:43:48,860 - services.trade_store - INFO - 날짜: 20241222, 포지션 수: 0건
2025-03-04 13:43:48,860 - services.trade_store - INFO - 날짜: 20241223, 포지션 수: 0건
2025-03-04 13:43:48,860 - services.trade_store - INFO - 날짜: 20241224, 포지션 수: 0건
2025-03-04 13:43:48,860 - services.trade_store - INFO - 날짜: 20241225, 포지션 수: 0건
2025-03-04 13:43:48,860 - services.trade_store - INFO - 날짜: 20241226, 포지션 수: 0건
2025-03-04 13:43:48,860 - services.trade_store - INFO - 날짜: 20241227, 포지션 수: 0건
2025-03-04 13:43:48,860 - services.trade_store - INFO - 날짜: 20241228, 포지션 수: 0건
2025-03-04 13:43:48,864 - services.trade_store - INFO - 날짜: 20241229, 포지션 수: 0건
2025-03-04 13:43:48,864 - services.trade_store - INFO - 날짜: 20241230, 포지션 수: 0건
2025-03-04 13:43:48,864 - services.trade_store - INFO - 날짜: 20241231, 포지션 수: 0건
2025-03-04 13:43:48,864 - services.trade_store - INFO - 날짜: 20250101, 포지션 수: 0건
2025-03-04 13:43:48,864 - services.trade_store - INFO - 날짜: 20250102, 포지션 수: 0건
2025-03-04 13:43:48,864 - services.trade_store - INFO - 날짜: 20250103, 포지션 수: 0건
2025-03-04 13:43:48,865 - services.trade_store - INFO - 날짜: 20250104, 포지션 수: 0건
2025-03-04 13:43:48,865 - services.trade_store - INFO - 날짜: 20250105, 포지션 수: 0건
2025-03-04 13:43:48,865 - services.trade_store - INFO - 날짜: 20250106, 포지션 수: 0건
2025-03-04 13:43:48,865 - services.trade_store - INFO - 날짜: 20250107, 포지션 수: 0건
2025-03-04 13:43:48,865 - services.trade_store - INFO - 날짜: 20250108, 포지션 수: 0건
2025-03-04 13:43:48,865 - services.trade_store - INFO - 날짜: 20250109, 포지션 수: 0건
2025-03-04 13:43:48,865 - services.trade_store - INFO - 날짜: 20250110, 포지션 수: 0건
2025-03-04 13:43:48,867 - services.trade_store - INFO - 날짜: 20250111, 포지션 수: 0건
2025-03-04 13:43:48,867 - services.trade_store - INFO - 날짜: 20250112, 포지션 수: 0건
2025-03-04 13:43:48,867 - services.trade_store - INFO - 날짜: 20250113, 포지션 수: 0건
2025-03-04 13:43:48,867 - services.trade_store - INFO - 날짜: 20250114, 포지션 수: 0건
2025-03-04 13:43:48,867 - services.trade_store - INFO - 날짜: 20250115, 포지션 수: 0건
2025-03-04 13:43:48,867 - services.trade_store - INFO - 날짜: 20250116, 포지션 수: 0건
2025-03-04 13:43:48,867 - services.trade_store - INFO - 날짜: 20250117, 포지션 수: 0건
2025-03-04 13:43:48,867 - services.trade_store - INFO - 날짜: 20250118, 포지션 수: 0건
2025-03-04 13:43:48,868 - services.trade_store - INFO - 날짜: 20250119, 포지션 수: 0건
2025-03-04 13:43:48,868 - services.trade_store - INFO - 날짜: 20250120, 포지션 수: 0건
2025-03-04 13:43:48,868 - services.trade_store - INFO - 날짜: 20250121, 포지션 수: 0건
2025-03-04 13:43:48,868 - services.trade_store - INFO - 날짜: 20250122, 포지션 수: 0건
2025-03-04 13:43:48,868 - services.trade_store - INFO - 날짜: 20250123, 포지션 수: 0건
2025-03-04 13:43:48,868 - services.trade_store - INFO - 날짜: 20250124, 포지션 수: 0건
2025-03-04 13:43:48,869 - services.trade_store - INFO - 날짜: 20250125, 포지션 수: 0건
2025-03-04 13:43:48,869 - services.trade_store - INFO - 날짜: 20250126, 포지션 수: 0건
2025-03-04 13:43:48,869 - services.trade_store - INFO - 날짜: 20250127, 포지션 수: 0건
2025-03-04 13:43:48,869 - services.trade_store - INFO - 날짜: 20250128, 포지션 수: 0건
2025-03-04 13:43:48,869 - services.trade_store - INFO - 날짜: 20250129, 포지션 수: 0건
2025-03-04 13:43:48,869 - services.trade_store - INFO - 날짜: 20250130, 포지션 수: 0건
2025-03-04 13:43:48,869 - services.trade_store - INFO - 날짜: 20250131, 포지션 수: 0건
2025-03-04 13:43:48,869 - services.trade_store - INFO - 날짜: 20250201, 포지션 수: 0건
2025-03-04 13:43:48,869 - services.trade_store - INFO - 날짜: 20250202, 포지션 수: 0건
2025-03-04 13:43:48,869 - services.trade_store - INFO - 날짜: 20250203, 포지션 수: 0건
2025-03-04 13:43:48,869 - services.trade_store - INFO - 날짜: 20250204, 포지션 수: 0건
2025-03-04 13:43:48,869 - services.trade_store - INFO - 날짜: 20250205, 포지션 수: 0건
2025-03-04 13:43:48,869 - services.trade_store - INFO - 날짜: 20250206, 포지션 수: 0건
2025-03-04 13:43:48,869 - services.trade_store - INFO - 날짜: 20250207, 포지션 수: 0건
2025-03-04 13:43:48,869 - services.trade_store - INFO - 날짜: 20250208, 포지션 수: 0건
2025-03-04 13:43:48,869 - services.trade_store - INFO - 날짜: 20250209, 포지션 수: 0건
2025-03-04 13:43:48,869 - services.trade_store - INFO - 날짜: 20250210, 포지션 수: 0건
2025-03-04 13:43:48,869 - services.trade_store - INFO - 날짜: 20250211, 포지션 수: 0건
2025-03-04 13:43:48,869 - services.trade_store - INFO - 날짜: 20250212, 포지션 수: 0건
2025-03-04 13:43:48,869 - services.trade_store - INFO - 날짜: 20250213, 포지션 수: 0건
2025-03-04 13:43:48,869 - services.trade_store - INFO - 날짜: 20250214, 포지션 수: 0건
2025-03-04 13:43:48,869 - services.trade_store - INFO - 날짜: 20250215, 포지션 수: 0건
2025-03-04 13:43:48,869 - services.trade_store - INFO - 날짜: 20250216, 포지션 수: 0건
2025-03-04 13:43:48,869 - services.trade_store - INFO - 날짜: 20250217, 포지션 수: 0건
2025-03-04 13:43:48,869 - services.trade_store - INFO - 날짜: 20250218, 포지션 수: 0건
2025-03-04 13:43:48,869 - services.trade_store - INFO - 날짜: 20250219, 포지션 수: 0건
2025-03-04 13:43:48,869 - services.trade_store - INFO - 날짜: 20250220, 포지션 수: 0건
2025-03-04 13:43:48,869 - services.trade_store - INFO - 날짜: 20250221, 포지션 수: 0건
2025-03-04 13:43:48,869 - services.trade_store - INFO - 날짜: 20250222, 포지션 수: 0건
2025-03-04 13:43:48,875 - services.trade_store - INFO - 날짜: 20250223, 포지션 수: 0건
2025-03-04 13:43:48,875 - services.trade_store - INFO - 날짜: 20250224, 포지션 수: 0건
2025-03-04 13:43:48,875 - services.trade_store - INFO - 날짜: 20250225, 포지션 수: 0건
2025-03-04 13:43:48,875 - services.trade_store - INFO - 날짜: 20250226, 포지션 수: 0건
2025-03-04 13:43:48,875 - services.trade_store - INFO - 날짜: 20250227, 포지션 수: 0건
2025-03-04 13:43:48,875 - services.trade_store - INFO - 날짜: 20250228, 포지션 수: 0건
2025-03-04 13:43:48,876 - services.trade_store - INFO - 날짜: 20250301, 포지션 수: 0건
2025-03-04 13:43:48,876 - services.trade_store - INFO - 날짜: 20250302, 포지션 수: 0건
2025-03-04 13:43:48,876 - services.trade_store - INFO - 날짜: 20250303, 포지션 수: 0건
2025-03-04 13:43:48,876 - services.trade_store - INFO - 날짜: 20250304, 포지션 수: 0건
2025-03-04 13:43:48,876 - services.trade_store - INFO - 총 0건의 포지션 데이터 로드됨
2025-03-04 13:43:48,876 - services.trade_history_service - INFO - 기존 데이터: 0건
2025-03-04 13:43:48,876 - services.trade_history_service - INFO - 기존 데이터가 없습니다. 전체 기간 조회를 시작합니다.
2025-03-04 13:43:48,876 - services.trade_history_service - INFO - 기간별 조회: 2024-12-04 ~ 2024-12-11
2025-03-04 13:43:48,876 - services.trade_history_service - DEBUG - API 요청 파라미터: {'category': 'linear', 'symbol': 'BTCUSDT', 'startTime': '1733287428860', 'endTime': '1733892228860', 'limit': 100}
2025-03-04 13:43:48,978 - exchange.bybit_client - INFO - 서버 시간 동기화 완료: offset = 831ms
2025-03-04 13:43:49,110 - services.trade_history_service - DEBUG - API 응답: {'retCode': 10004, 'retMsg': 'error sign! origin_string[1741063429809yjHTlVOB6X6Man1Ah520000category=linear&symbol=BTCUSDT&startTime=1733287428860&endTime=1733892228860&limit=100&timestamp=1741063429809]', 'result': {}, 'retExtInfo': {}, 'time': 1741063429941}
2025-03-04 13:43:50,116 - services.trade_history_service - INFO - 기간별 조회: 2024-12-11 ~ 2024-12-18
2025-03-04 13:43:50,116 - services.trade_history_service - DEBUG - API 요청 파라미터: {'category': 'linear', 'symbol': 'BTCUSDT', 'startTime': '1733892228860', 'endTime': '1734497028860', 'limit': 100}
2025-03-04 13:43:50,229 - services.trade_history_service - DEBUG - API 응답: {'retCode': 10004, 'retMsg': 'error sign! origin_string[1741063430947yjHTlVOB6X6Man1Ah520000category=linear&symbol=BTCUSDT&startTime=1733892228860&endTime=1734497028860&limit=100&timestamp=1741063430947]', 'result': {}, 'retExtInfo': {}, 'time': 1741063431054}
2025-03-04 13:43:51,246 - services.trade_history_service - INFO - 기간별 조회: 2024-12-18 ~ 2024-12-25
2025-03-04 13:43:51,246 - services.trade_history_service - DEBUG - API 요청 파라미터: {'category': 'linear', 'symbol': 'BTCUSDT', 'startTime': '1734497028860', 'endTime': '1735101828860', 'limit': 100}
2025-03-04 13:43:51,361 - services.trade_history_service - DEBUG - API 응답: {'retCode': 10004, 'retMsg': 'error sign! origin_string[1741063432077yjHTlVOB6X6Man1Ah520000category=linear&symbol=BTCUSDT&startTime=1734497028860&endTime=1735101828860&limit=100&timestamp=1741063432077]', 'result': {}, 'retExtInfo': {}, 'time': 1741063432175}
2025-03-04 13:43:52,363 - services.trade_history_service - INFO - 기간별 조회: 2024-12-25 ~ 2025-01-01
2025-03-04 13:43:52,363 - services.trade_history_service - DEBUG - API 요청 파라미터: {'category': 'linear', 'symbol': 'BTCUSDT', 'startTime': '1735101828860', 'endTime': '1735706628860', 'limit': 100}
2025-03-04 13:43:52,482 - services.trade_history_service - DEBUG - API 응답: {'retCode': 10004, 'retMsg': 'error sign! origin_string[1741063433194yjHTlVOB6X6Man1Ah520000category=linear&symbol=BTCUSDT&startTime=1735101828860&endTime=1735706628860&limit=100&timestamp=1741063433194]', 'result': {}, 'retExtInfo': {}, 'time': 1741063433298}
2025-03-04 13:43:53,488 - services.trade_history_service - INFO - 기간별 조회: 2025-01-01 ~ 2025-01-08
2025-03-04 13:43:53,488 - services.trade_history_service - DEBUG - API 요청 파라미터: {'category': 'linear', 'symbol': 'BTCUSDT', 'startTime': '1735706628860', 'endTime': '1736311428860', 'limit': 100}
2025-03-04 13:43:53,597 - services.trade_history_service - DEBUG - API 응답: {'retCode': 10004, 'retMsg': 'error sign! origin_string[1741063434320yjHTlVOB6X6Man1Ah520000category=linear&symbol=BTCUSDT&startTime=1735706628860&endTime=1736311428860&limit=100&timestamp=1741063434320]', 'result': {}, 'retExtInfo': {}, 'time': 1741063434413}
2025-03-04 13:43:54,613 - services.trade_history_service - INFO - 기간별 조회: 2025-01-08 ~ 2025-01-15
2025-03-04 13:43:54,613 - services.trade_history_service - DEBUG - API 요청 파라미터: {'category': 'linear', 'symbol': 'BTCUSDT', 'startTime': '1736311428860', 'endTime': '1736916228860', 'limit': 100}
2025-03-04 13:43:54,715 - services.trade_history_service - DEBUG - API 응답: {'retCode': 10004, 'retMsg': 'error sign! origin_string[1741063435444yjHTlVOB6X6Man1Ah520000category=linear&symbol=BTCUSDT&startTime=1736311428860&endTime=1736916228860&limit=100&timestamp=1741063435444]', 'result': {}, 'retExtInfo': {}, 'time': 1741063435539}
2025-03-04 13:43:55,714 - services.trade_history_service - INFO - 기간별 조회: 2025-01-15 ~ 2025-01-22
2025-03-04 13:43:55,714 - services.trade_history_service - DEBUG - API 요청 파라미터: {'category': 'linear', 'symbol': 'BTCUSDT', 'startTime': '1736916228860', 'endTime': '1737521028860', 'limit': 100}
2025-03-04 13:43:55,830 - services.trade_history_service - DEBUG - API 응답: {'retCode': 10004, 'retMsg': 'error sign! origin_string[1741063436545yjHTlVOB6X6Man1Ah520000category=linear&symbol=BTCUSDT&startTime=1736916228860&endTime=1737521028860&limit=100&timestamp=1741063436545]', 'result': {}, 'retExtInfo': {}, 'time': 1741063436652}
2025-03-04 13:43:56,843 - services.trade_history_service - INFO - 기간별 조회: 2025-01-22 ~ 2025-01-29
2025-03-04 13:43:56,843 - services.trade_history_service - DEBUG - API 요청 파라미터: {'category': 'linear', 'symbol': 'BTCUSDT', 'startTime': '1737521028860', 'endTime': '1738125828860', 'limit': 100}
2025-03-04 13:43:56,948 - services.trade_history_service - DEBUG - API 응답: {'retCode': 10004, 'retMsg': 'error sign! origin_string[1741063437674yjHTlVOB6X6Man1Ah520000category=linear&symbol=BTCUSDT&startTime=1737521028860&endTime=1738125828860&limit=100&timestamp=1741063437674]', 'result': {}, 'retExtInfo': {}, 'time': 1741063437768}
2025-03-04 13:43:57,963 - services.trade_history_service - INFO - 기간별 조회: 2025-01-29 ~ 2025-02-05
2025-03-04 13:43:57,963 - services.trade_history_service - DEBUG - API 요청 파라미터: {'category': 'linear', 'symbol': 'BTCUSDT', 'startTime': '1738125828860', 'endTime': '1738730628860', 'limit': 100}
2025-03-04 13:43:58,209 - services.trade_history_service - DEBUG - API 응답: {'retCode': 10004, 'retMsg': 'error sign! origin_string[1741063438794yjHTlVOB6X6Man1Ah520000category=linear&symbol=BTCUSDT&startTime=1738125828860&endTime=1738730628860&limit=100&timestamp=1741063438794]', 'result': {}, 'retExtInfo': {}, 'time': 1741063439025}
2025-03-04 13:43:59,222 - services.trade_history_service - INFO - 기간별 조회: 2025-02-05 ~ 2025-02-12
2025-03-04 13:43:59,222 - services.trade_history_service - DEBUG - API 요청 파라미터: {'category': 'linear', 'symbol': 'BTCUSDT', 'startTime': '1738730628860', 'endTime': '1739335428860', 'limit': 100}
2025-03-04 13:43:59,323 - services.trade_history_service - DEBUG - API 응답: {'retCode': 10004, 'retMsg': 'error sign! origin_string[1741063440053yjHTlVOB6X6Man1Ah520000category=linear&symbol=BTCUSDT&startTime=1738730628860&endTime=1739335428860&limit=100&timestamp=1741063440053]', 'result': {}, 'retExtInfo': {}, 'time': 1741063440143}
2025-03-04 13:44:00,334 - services.trade_history_service - INFO - 기간별 조회: 2025-02-12 ~ 2025-02-19
2025-03-04 13:44:00,334 - services.trade_history_service - DEBUG - API 요청 파라미터: {'category': 'linear', 'symbol': 'BTCUSDT', 'startTime': '1739335428860', 'endTime': '1739940228860', 'limit': 100}
2025-03-04 13:44:00,441 - services.trade_history_service - DEBUG - API 응답: {'retCode': 10004, 'retMsg': 'error sign! origin_string[1741063441165yjHTlVOB6X6Man1Ah520000category=linear&symbol=BTCUSDT&startTime=1739335428860&endTime=1739940228860&limit=100&timestamp=1741063441165]', 'result': {}, 'retExtInfo': {}, 'time': 1741063441264}
2025-03-04 13:44:01,447 - services.trade_history_service - INFO - 기간별 조회: 2025-02-19 ~ 2025-02-26
2025-03-04 13:44:01,447 - services.trade_history_service - DEBUG - API 요청 파라미터: {'category': 'linear', 'symbol': 'BTCUSDT', 'startTime': '1739940228860', 'endTime': '1740545028860', 'limit': 100}
2025-03-04 13:44:01,557 - services.trade_history_service - DEBUG - API 응답: {'retCode': 10004, 'retMsg': 'error sign! origin_string[1741063442278yjHTlVOB6X6Man1Ah520000category=linear&symbol=BTCUSDT&startTime=1739940228860&endTime=1740545028860&limit=100&timestamp=1741063442278]', 'result': {}, 'retExtInfo': {}, 'time': 1741063442374}
2025-03-04 13:44:02,566 - services.trade_history_service - INFO - 기간별 조회: 2025-02-26 ~ 2025-03-04
2025-03-04 13:44:02,566 - services.trade_history_service - DEBUG - API 요청 파라미터: {'category': 'linear', 'symbol': 'BTCUSDT', 'startTime': '1740545028860', 'endTime': '1741063428860', 'limit': 100}
2025-03-04 13:44:02,671 - services.trade_history_service - DEBUG - API 응답: {'retCode': 10004, 'retMsg': 'error sign! origin_string[1741063443399yjHTlVOB6X6Man1Ah520000category=linear&symbol=BTCUSDT&startTime=1740545028860&endTime=1741063428860&limit=100&timestamp=1741063443399]', 'result': {}, 'retExtInfo': {}, 'time': 1741063443498}
2025-03-04 13:44:03,682 - telegram_bot.bot - INFO - Application 빌드 시작...
2025-03-04 13:44:04,053 - apscheduler.scheduler - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2025-03-04 13:44:04,070 - telegram_bot.bot - INFO - 핸들러 초기화 완료
2025-03-04 13:44:04,070 - telegram_bot.bot - INFO - 봇 초기화 완료, 시작 준비 중...
2025-03-04 13:44:04,070 - telegram_bot.bot - INFO - 봇 시작 시도...
2025-03-04 13:44:04,070 - telegram_bot.bot - INFO - === 봇 시작 시도 ===
2025-03-04 13:44:05,918 - apscheduler.scheduler - INFO - Scheduler started
2025-03-04 13:44:05,918 - telegram.ext.Application - INFO - Application started
2025-03-04 13:44:06,185 - telegram_bot.bot - INFO - 🤖 바이빗 트레이딩 봇이 시작되었습니다
2025-03-04 14:13:51,370 - telegram.ext.Updater - ERROR - Error while getting Updates: httpx.ConnectError: [Errno 11001] getaddrinfo failed
2025-03-04 14:13:51,373 - telegram.ext.Updater - ERROR - Exception happened while polling for updates.
Traceback (most recent call last):
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpx\_transports\default.py", line 66, in map_httpcore_exceptions
    yield
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpx\_transports\default.py", line 366, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 256, in handle_async_request
    raise exc from None
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 236, in handle_async_request
    response = await connection.handle_async_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpcore\_async\connection.py", line 101, in handle_async_request
    raise exc
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpcore\_async\connection.py", line 78, in handle_async_request
    stream = await self._connect(request)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpcore\_async\connection.py", line 124, in _connect
    stream = await self._network_backend.connect_tcp(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpcore\_backends\auto.py", line 31, in connect_tcp
    return await self._backend.connect_tcp(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpcore\_backends\anyio.py", line 113, in connect_tcp
    with map_exceptions(exc_map):
  File "C:\Program Files\Python311\Lib\contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpcore\_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectError: [Errno 11001] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\request\_httpxrequest.py", line 268, in do_request
    res = await self._client.request(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpx\_client.py", line 1530, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpx\_client.py", line 1617, in send
    response = await self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpx\_client.py", line 1645, in _send_handling_auth
    response = await self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpx\_client.py", line 1682, in _send_handling_redirects
    response = await self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpx\_client.py", line 1719, in _send_single_request
    response = await transport.handle_async_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpx\_transports\default.py", line 365, in handle_async_request
    with map_httpcore_exceptions():
  File "C:\Program Files\Python311\Lib\contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpx\_transports\default.py", line 83, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: [Errno 11001] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\ext\_updater.py", line 688, in _network_loop_retry
    if not await action_cb():
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\ext\_updater.py", line 384, in polling_action_cb
    raise exc
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\ext\_updater.py", line 373, in polling_action_cb
    updates = await self.bot.get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\ext\_extbot.py", line 558, in get_updates
    updates = await super().get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\_bot.py", line 525, in decorator
    result = await func(self, *args, **kwargs)  # skipcq: PYL-E1102
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\_bot.py", line 3584, in get_updates
    await self._post(
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\_bot.py", line 613, in _post
    return await self._do_post(
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\ext\_extbot.py", line 340, in _do_post
    return await super()._do_post(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\_bot.py", line 641, in _do_post
    return await request.post(
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\request\_baserequest.py", line 200, in post
    result = await self._request_wrapper(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\request\_baserequest.py", line 340, in _request_wrapper
    raise exc
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\request\_baserequest.py", line 330, in _request_wrapper
    code, payload = await self.do_request(
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\request\_httpxrequest.py", line 292, in do_request
    raise NetworkError(f"httpx.{err.__class__.__name__}: {err}") from err
telegram.error.NetworkError: httpx.ConnectError: [Errno 11001] getaddrinfo failed
2025-03-04 14:18:04,519 - telegram.ext.Updater - ERROR - Error while getting Updates: httpx.ConnectError: [Errno 11001] getaddrinfo failed
2025-03-04 14:18:04,520 - telegram.ext.Updater - ERROR - Exception happened while polling for updates.
Traceback (most recent call last):
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpx\_transports\default.py", line 66, in map_httpcore_exceptions
    yield
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpx\_transports\default.py", line 366, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 256, in handle_async_request
    raise exc from None
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 236, in handle_async_request
    response = await connection.handle_async_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpcore\_async\connection.py", line 101, in handle_async_request
    raise exc
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpcore\_async\connection.py", line 78, in handle_async_request
    stream = await self._connect(request)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpcore\_async\connection.py", line 124, in _connect
    stream = await self._network_backend.connect_tcp(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpcore\_backends\auto.py", line 31, in connect_tcp
    return await self._backend.connect_tcp(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpcore\_backends\anyio.py", line 113, in connect_tcp
    with map_exceptions(exc_map):
  File "C:\Program Files\Python311\Lib\contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpcore\_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectError: [Errno 11001] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\request\_httpxrequest.py", line 268, in do_request
    res = await self._client.request(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpx\_client.py", line 1530, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpx\_client.py", line 1617, in send
    response = await self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpx\_client.py", line 1645, in _send_handling_auth
    response = await self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpx\_client.py", line 1682, in _send_handling_redirects
    response = await self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpx\_client.py", line 1719, in _send_single_request
    response = await transport.handle_async_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpx\_transports\default.py", line 365, in handle_async_request
    with map_httpcore_exceptions():
  File "C:\Program Files\Python311\Lib\contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpx\_transports\default.py", line 83, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: [Errno 11001] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\ext\_updater.py", line 688, in _network_loop_retry
    if not await action_cb():
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\ext\_updater.py", line 384, in polling_action_cb
    raise exc
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\ext\_updater.py", line 373, in polling_action_cb
    updates = await self.bot.get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\ext\_extbot.py", line 558, in get_updates
    updates = await super().get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\_bot.py", line 525, in decorator
    result = await func(self, *args, **kwargs)  # skipcq: PYL-E1102
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\_bot.py", line 3584, in get_updates
    await self._post(
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\_bot.py", line 613, in _post
    return await self._do_post(
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\ext\_extbot.py", line 340, in _do_post
    return await super()._do_post(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\_bot.py", line 641, in _do_post
    return await request.post(
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\request\_baserequest.py", line 200, in post
    result = await self._request_wrapper(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\request\_baserequest.py", line 340, in _request_wrapper
    raise exc
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\request\_baserequest.py", line 330, in _request_wrapper
    code, payload = await self.do_request(
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\request\_httpxrequest.py", line 292, in do_request
    raise NetworkError(f"httpx.{err.__class__.__name__}: {err}") from err
telegram.error.NetworkError: httpx.ConnectError: [Errno 11001] getaddrinfo failed
2025-03-04 14:18:05,533 - telegram.ext.Updater - ERROR - Error while getting Updates: httpx.ConnectError: [Errno 11001] getaddrinfo failed
2025-03-04 14:18:05,535 - telegram.ext.Updater - ERROR - Exception happened while polling for updates.
Traceback (most recent call last):
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpx\_transports\default.py", line 66, in map_httpcore_exceptions
    yield
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpx\_transports\default.py", line 366, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 256, in handle_async_request
    raise exc from None
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 236, in handle_async_request
    response = await connection.handle_async_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpcore\_async\connection.py", line 101, in handle_async_request
    raise exc
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpcore\_async\connection.py", line 78, in handle_async_request
    stream = await self._connect(request)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpcore\_async\connection.py", line 124, in _connect
    stream = await self._network_backend.connect_tcp(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpcore\_backends\auto.py", line 31, in connect_tcp
    return await self._backend.connect_tcp(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpcore\_backends\anyio.py", line 113, in connect_tcp
    with map_exceptions(exc_map):
  File "C:\Program Files\Python311\Lib\contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpcore\_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectError: [Errno 11001] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\request\_httpxrequest.py", line 268, in do_request
    res = await self._client.request(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpx\_client.py", line 1530, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpx\_client.py", line 1617, in send
    response = await self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpx\_client.py", line 1645, in _send_handling_auth
    response = await self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpx\_client.py", line 1682, in _send_handling_redirects
    response = await self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpx\_client.py", line 1719, in _send_single_request
    response = await transport.handle_async_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpx\_transports\default.py", line 365, in handle_async_request
    with map_httpcore_exceptions():
  File "C:\Program Files\Python311\Lib\contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpx\_transports\default.py", line 83, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: [Errno 11001] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\ext\_updater.py", line 688, in _network_loop_retry
    if not await action_cb():
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\ext\_updater.py", line 384, in polling_action_cb
    raise exc
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\ext\_updater.py", line 373, in polling_action_cb
    updates = await self.bot.get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\ext\_extbot.py", line 558, in get_updates
    updates = await super().get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\_bot.py", line 525, in decorator
    result = await func(self, *args, **kwargs)  # skipcq: PYL-E1102
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\_bot.py", line 3584, in get_updates
    await self._post(
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\_bot.py", line 613, in _post
    return await self._do_post(
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\ext\_extbot.py", line 340, in _do_post
    return await super()._do_post(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\_bot.py", line 641, in _do_post
    return await request.post(
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\request\_baserequest.py", line 200, in post
    result = await self._request_wrapper(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\request\_baserequest.py", line 340, in _request_wrapper
    raise exc
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\request\_baserequest.py", line 330, in _request_wrapper
    code, payload = await self.do_request(
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\request\_httpxrequest.py", line 292, in do_request
    raise NetworkError(f"httpx.{err.__class__.__name__}: {err}") from err
telegram.error.NetworkError: httpx.ConnectError: [Errno 11001] getaddrinfo failed
2025-03-04 14:18:07,054 - telegram.ext.Updater - ERROR - Error while getting Updates: httpx.ConnectError: [Errno 11001] getaddrinfo failed
2025-03-04 14:18:07,055 - telegram.ext.Updater - ERROR - Exception happened while polling for updates.
Traceback (most recent call last):
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpx\_transports\default.py", line 66, in map_httpcore_exceptions
    yield
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpx\_transports\default.py", line 366, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 256, in handle_async_request
    raise exc from None
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 236, in handle_async_request
    response = await connection.handle_async_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpcore\_async\connection.py", line 101, in handle_async_request
    raise exc
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpcore\_async\connection.py", line 78, in handle_async_request
    stream = await self._connect(request)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpcore\_async\connection.py", line 124, in _connect
    stream = await self._network_backend.connect_tcp(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpcore\_backends\auto.py", line 31, in connect_tcp
    return await self._backend.connect_tcp(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpcore\_backends\anyio.py", line 113, in connect_tcp
    with map_exceptions(exc_map):
  File "C:\Program Files\Python311\Lib\contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpcore\_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectError: [Errno 11001] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\request\_httpxrequest.py", line 268, in do_request
    res = await self._client.request(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpx\_client.py", line 1530, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpx\_client.py", line 1617, in send
    response = await self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpx\_client.py", line 1645, in _send_handling_auth
    response = await self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpx\_client.py", line 1682, in _send_handling_redirects
    response = await self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpx\_client.py", line 1719, in _send_single_request
    response = await transport.handle_async_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpx\_transports\default.py", line 365, in handle_async_request
    with map_httpcore_exceptions():
  File "C:\Program Files\Python311\Lib\contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpx\_transports\default.py", line 83, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: [Errno 11001] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\ext\_updater.py", line 688, in _network_loop_retry
    if not await action_cb():
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\ext\_updater.py", line 384, in polling_action_cb
    raise exc
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\ext\_updater.py", line 373, in polling_action_cb
    updates = await self.bot.get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\ext\_extbot.py", line 558, in get_updates
    updates = await super().get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\_bot.py", line 525, in decorator
    result = await func(self, *args, **kwargs)  # skipcq: PYL-E1102
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\_bot.py", line 3584, in get_updates
    await self._post(
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\_bot.py", line 613, in _post
    return await self._do_post(
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\ext\_extbot.py", line 340, in _do_post
    return await super()._do_post(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\_bot.py", line 641, in _do_post
    return await request.post(
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\request\_baserequest.py", line 200, in post
    result = await self._request_wrapper(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\request\_baserequest.py", line 340, in _request_wrapper
    raise exc
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\request\_baserequest.py", line 330, in _request_wrapper
    code, payload = await self.do_request(
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\request\_httpxrequest.py", line 292, in do_request
    raise NetworkError(f"httpx.{err.__class__.__name__}: {err}") from err
telegram.error.NetworkError: httpx.ConnectError: [Errno 11001] getaddrinfo failed
2025-03-04 14:18:09,318 - telegram.ext.Updater - ERROR - Error while getting Updates: httpx.ConnectError: [Errno 11001] getaddrinfo failed
2025-03-04 14:18:09,319 - telegram.ext.Updater - ERROR - Exception happened while polling for updates.
Traceback (most recent call last):
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpx\_transports\default.py", line 66, in map_httpcore_exceptions
    yield
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpx\_transports\default.py", line 366, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 256, in handle_async_request
    raise exc from None
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 236, in handle_async_request
    response = await connection.handle_async_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpcore\_async\connection.py", line 101, in handle_async_request
    raise exc
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpcore\_async\connection.py", line 78, in handle_async_request
    stream = await self._connect(request)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpcore\_async\connection.py", line 124, in _connect
    stream = await self._network_backend.connect_tcp(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpcore\_backends\auto.py", line 31, in connect_tcp
    return await self._backend.connect_tcp(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpcore\_backends\anyio.py", line 113, in connect_tcp
    with map_exceptions(exc_map):
  File "C:\Program Files\Python311\Lib\contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpcore\_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectError: [Errno 11001] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\request\_httpxrequest.py", line 268, in do_request
    res = await self._client.request(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpx\_client.py", line 1530, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpx\_client.py", line 1617, in send
    response = await self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpx\_client.py", line 1645, in _send_handling_auth
    response = await self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpx\_client.py", line 1682, in _send_handling_redirects
    response = await self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpx\_client.py", line 1719, in _send_single_request
    response = await transport.handle_async_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpx\_transports\default.py", line 365, in handle_async_request
    with map_httpcore_exceptions():
  File "C:\Program Files\Python311\Lib\contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpx\_transports\default.py", line 83, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: [Errno 11001] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\ext\_updater.py", line 688, in _network_loop_retry
    if not await action_cb():
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\ext\_updater.py", line 384, in polling_action_cb
    raise exc
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\ext\_updater.py", line 373, in polling_action_cb
    updates = await self.bot.get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\ext\_extbot.py", line 558, in get_updates
    updates = await super().get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\_bot.py", line 525, in decorator
    result = await func(self, *args, **kwargs)  # skipcq: PYL-E1102
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\_bot.py", line 3584, in get_updates
    await self._post(
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\_bot.py", line 613, in _post
    return await self._do_post(
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\ext\_extbot.py", line 340, in _do_post
    return await super()._do_post(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\_bot.py", line 641, in _do_post
    return await request.post(
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\request\_baserequest.py", line 200, in post
    result = await self._request_wrapper(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\request\_baserequest.py", line 340, in _request_wrapper
    raise exc
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\request\_baserequest.py", line 330, in _request_wrapper
    code, payload = await self.do_request(
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\request\_httpxrequest.py", line 292, in do_request
    raise NetworkError(f"httpx.{err.__class__.__name__}: {err}") from err
telegram.error.NetworkError: httpx.ConnectError: [Errno 11001] getaddrinfo failed
2025-03-04 14:18:12,703 - telegram.ext.Updater - ERROR - Error while getting Updates: httpx.ConnectError: [Errno 11001] getaddrinfo failed
2025-03-04 14:18:12,704 - telegram.ext.Updater - ERROR - Exception happened while polling for updates.
Traceback (most recent call last):
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpx\_transports\default.py", line 66, in map_httpcore_exceptions
    yield
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpx\_transports\default.py", line 366, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 256, in handle_async_request
    raise exc from None
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 236, in handle_async_request
    response = await connection.handle_async_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpcore\_async\connection.py", line 101, in handle_async_request
    raise exc
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpcore\_async\connection.py", line 78, in handle_async_request
    stream = await self._connect(request)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpcore\_async\connection.py", line 124, in _connect
    stream = await self._network_backend.connect_tcp(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpcore\_backends\auto.py", line 31, in connect_tcp
    return await self._backend.connect_tcp(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpcore\_backends\anyio.py", line 113, in connect_tcp
    with map_exceptions(exc_map):
  File "C:\Program Files\Python311\Lib\contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpcore\_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectError: [Errno 11001] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\request\_httpxrequest.py", line 268, in do_request
    res = await self._client.request(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpx\_client.py", line 1530, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpx\_client.py", line 1617, in send
    response = await self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpx\_client.py", line 1645, in _send_handling_auth
    response = await self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpx\_client.py", line 1682, in _send_handling_redirects
    response = await self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpx\_client.py", line 1719, in _send_single_request
    response = await transport.handle_async_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpx\_transports\default.py", line 365, in handle_async_request
    with map_httpcore_exceptions():
  File "C:\Program Files\Python311\Lib\contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpx\_transports\default.py", line 83, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: [Errno 11001] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\ext\_updater.py", line 688, in _network_loop_retry
    if not await action_cb():
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\ext\_updater.py", line 384, in polling_action_cb
    raise exc
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\ext\_updater.py", line 373, in polling_action_cb
    updates = await self.bot.get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\ext\_extbot.py", line 558, in get_updates
    updates = await super().get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\_bot.py", line 525, in decorator
    result = await func(self, *args, **kwargs)  # skipcq: PYL-E1102
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\_bot.py", line 3584, in get_updates
    await self._post(
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\_bot.py", line 613, in _post
    return await self._do_post(
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\ext\_extbot.py", line 340, in _do_post
    return await super()._do_post(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\_bot.py", line 641, in _do_post
    return await request.post(
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\request\_baserequest.py", line 200, in post
    result = await self._request_wrapper(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\request\_baserequest.py", line 340, in _request_wrapper
    raise exc
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\request\_baserequest.py", line 330, in _request_wrapper
    code, payload = await self.do_request(
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\request\_httpxrequest.py", line 292, in do_request
    raise NetworkError(f"httpx.{err.__class__.__name__}: {err}") from err
telegram.error.NetworkError: httpx.ConnectError: [Errno 11001] getaddrinfo failed
2025-03-04 14:18:17,787 - telegram.ext.Updater - ERROR - Error while getting Updates: httpx.ConnectError: [Errno 11001] getaddrinfo failed
2025-03-04 14:18:17,788 - telegram.ext.Updater - ERROR - Exception happened while polling for updates.
Traceback (most recent call last):
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpx\_transports\default.py", line 66, in map_httpcore_exceptions
    yield
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpx\_transports\default.py", line 366, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 256, in handle_async_request
    raise exc from None
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 236, in handle_async_request
    response = await connection.handle_async_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpcore\_async\connection.py", line 101, in handle_async_request
    raise exc
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpcore\_async\connection.py", line 78, in handle_async_request
    stream = await self._connect(request)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpcore\_async\connection.py", line 124, in _connect
    stream = await self._network_backend.connect_tcp(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpcore\_backends\auto.py", line 31, in connect_tcp
    return await self._backend.connect_tcp(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpcore\_backends\anyio.py", line 113, in connect_tcp
    with map_exceptions(exc_map):
  File "C:\Program Files\Python311\Lib\contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpcore\_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectError: [Errno 11001] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\request\_httpxrequest.py", line 268, in do_request
    res = await self._client.request(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpx\_client.py", line 1530, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpx\_client.py", line 1617, in send
    response = await self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpx\_client.py", line 1645, in _send_handling_auth
    response = await self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpx\_client.py", line 1682, in _send_handling_redirects
    response = await self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpx\_client.py", line 1719, in _send_single_request
    response = await transport.handle_async_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpx\_transports\default.py", line 365, in handle_async_request
    with map_httpcore_exceptions():
  File "C:\Program Files\Python311\Lib\contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpx\_transports\default.py", line 83, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: [Errno 11001] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\ext\_updater.py", line 688, in _network_loop_retry
    if not await action_cb():
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\ext\_updater.py", line 384, in polling_action_cb
    raise exc
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\ext\_updater.py", line 373, in polling_action_cb
    updates = await self.bot.get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\ext\_extbot.py", line 558, in get_updates
    updates = await super().get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\_bot.py", line 525, in decorator
    result = await func(self, *args, **kwargs)  # skipcq: PYL-E1102
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\_bot.py", line 3584, in get_updates
    await self._post(
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\_bot.py", line 613, in _post
    return await self._do_post(
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\ext\_extbot.py", line 340, in _do_post
    return await super()._do_post(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\_bot.py", line 641, in _do_post
    return await request.post(
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\request\_baserequest.py", line 200, in post
    result = await self._request_wrapper(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\request\_baserequest.py", line 340, in _request_wrapper
    raise exc
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\request\_baserequest.py", line 330, in _request_wrapper
    code, payload = await self.do_request(
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\request\_httpxrequest.py", line 292, in do_request
    raise NetworkError(f"httpx.{err.__class__.__name__}: {err}") from err
telegram.error.NetworkError: httpx.ConnectError: [Errno 11001] getaddrinfo failed
2025-03-04 14:18:25,394 - telegram.ext.Updater - ERROR - Error while getting Updates: httpx.ConnectError: [Errno 11001] getaddrinfo failed
2025-03-04 14:18:25,395 - telegram.ext.Updater - ERROR - Exception happened while polling for updates.
Traceback (most recent call last):
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpx\_transports\default.py", line 66, in map_httpcore_exceptions
    yield
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpx\_transports\default.py", line 366, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 256, in handle_async_request
    raise exc from None
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 236, in handle_async_request
    response = await connection.handle_async_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpcore\_async\connection.py", line 101, in handle_async_request
    raise exc
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpcore\_async\connection.py", line 78, in handle_async_request
    stream = await self._connect(request)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpcore\_async\connection.py", line 124, in _connect
    stream = await self._network_backend.connect_tcp(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpcore\_backends\auto.py", line 31, in connect_tcp
    return await self._backend.connect_tcp(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpcore\_backends\anyio.py", line 113, in connect_tcp
    with map_exceptions(exc_map):
  File "C:\Program Files\Python311\Lib\contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpcore\_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectError: [Errno 11001] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\request\_httpxrequest.py", line 268, in do_request
    res = await self._client.request(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpx\_client.py", line 1530, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpx\_client.py", line 1617, in send
    response = await self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpx\_client.py", line 1645, in _send_handling_auth
    response = await self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpx\_client.py", line 1682, in _send_handling_redirects
    response = await self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpx\_client.py", line 1719, in _send_single_request
    response = await transport.handle_async_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpx\_transports\default.py", line 365, in handle_async_request
    with map_httpcore_exceptions():
  File "C:\Program Files\Python311\Lib\contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpx\_transports\default.py", line 83, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: [Errno 11001] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\ext\_updater.py", line 688, in _network_loop_retry
    if not await action_cb():
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\ext\_updater.py", line 384, in polling_action_cb
    raise exc
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\ext\_updater.py", line 373, in polling_action_cb
    updates = await self.bot.get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\ext\_extbot.py", line 558, in get_updates
    updates = await super().get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\_bot.py", line 525, in decorator
    result = await func(self, *args, **kwargs)  # skipcq: PYL-E1102
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\_bot.py", line 3584, in get_updates
    await self._post(
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\_bot.py", line 613, in _post
    return await self._do_post(
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\ext\_extbot.py", line 340, in _do_post
    return await super()._do_post(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\_bot.py", line 641, in _do_post
    return await request.post(
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\request\_baserequest.py", line 200, in post
    result = await self._request_wrapper(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\request\_baserequest.py", line 340, in _request_wrapper
    raise exc
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\request\_baserequest.py", line 330, in _request_wrapper
    code, payload = await self.do_request(
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\request\_httpxrequest.py", line 292, in do_request
    raise NetworkError(f"httpx.{err.__class__.__name__}: {err}") from err
telegram.error.NetworkError: httpx.ConnectError: [Errno 11001] getaddrinfo failed
2025-03-04 14:18:36,813 - telegram.ext.Updater - ERROR - Error while getting Updates: httpx.ConnectError: [Errno 11001] getaddrinfo failed
2025-03-04 14:18:36,814 - telegram.ext.Updater - ERROR - Exception happened while polling for updates.
Traceback (most recent call last):
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpx\_transports\default.py", line 66, in map_httpcore_exceptions
    yield
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpx\_transports\default.py", line 366, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 256, in handle_async_request
    raise exc from None
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 236, in handle_async_request
    response = await connection.handle_async_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpcore\_async\connection.py", line 101, in handle_async_request
    raise exc
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpcore\_async\connection.py", line 78, in handle_async_request
    stream = await self._connect(request)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpcore\_async\connection.py", line 124, in _connect
    stream = await self._network_backend.connect_tcp(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpcore\_backends\auto.py", line 31, in connect_tcp
    return await self._backend.connect_tcp(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpcore\_backends\anyio.py", line 113, in connect_tcp
    with map_exceptions(exc_map):
  File "C:\Program Files\Python311\Lib\contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpcore\_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectError: [Errno 11001] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\request\_httpxrequest.py", line 268, in do_request
    res = await self._client.request(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpx\_client.py", line 1530, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpx\_client.py", line 1617, in send
    response = await self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpx\_client.py", line 1645, in _send_handling_auth
    response = await self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpx\_client.py", line 1682, in _send_handling_redirects
    response = await self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpx\_client.py", line 1719, in _send_single_request
    response = await transport.handle_async_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpx\_transports\default.py", line 365, in handle_async_request
    with map_httpcore_exceptions():
  File "C:\Program Files\Python311\Lib\contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpx\_transports\default.py", line 83, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: [Errno 11001] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\ext\_updater.py", line 688, in _network_loop_retry
    if not await action_cb():
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\ext\_updater.py", line 384, in polling_action_cb
    raise exc
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\ext\_updater.py", line 373, in polling_action_cb
    updates = await self.bot.get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\ext\_extbot.py", line 558, in get_updates
    updates = await super().get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\_bot.py", line 525, in decorator
    result = await func(self, *args, **kwargs)  # skipcq: PYL-E1102
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\_bot.py", line 3584, in get_updates
    await self._post(
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\_bot.py", line 613, in _post
    return await self._do_post(
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\ext\_extbot.py", line 340, in _do_post
    return await super()._do_post(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\_bot.py", line 641, in _do_post
    return await request.post(
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\request\_baserequest.py", line 200, in post
    result = await self._request_wrapper(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\request\_baserequest.py", line 340, in _request_wrapper
    raise exc
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\request\_baserequest.py", line 330, in _request_wrapper
    code, payload = await self.do_request(
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\request\_httpxrequest.py", line 292, in do_request
    raise NetworkError(f"httpx.{err.__class__.__name__}: {err}") from err
telegram.error.NetworkError: httpx.ConnectError: [Errno 11001] getaddrinfo failed
2025-03-04 14:18:53,917 - telegram.ext.Updater - ERROR - Error while getting Updates: httpx.ConnectError: [Errno 11001] getaddrinfo failed
2025-03-04 14:18:53,919 - telegram.ext.Updater - ERROR - Exception happened while polling for updates.
Traceback (most recent call last):
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpx\_transports\default.py", line 66, in map_httpcore_exceptions
    yield
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpx\_transports\default.py", line 366, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 256, in handle_async_request
    raise exc from None
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 236, in handle_async_request
    response = await connection.handle_async_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpcore\_async\connection.py", line 101, in handle_async_request
    raise exc
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpcore\_async\connection.py", line 78, in handle_async_request
    stream = await self._connect(request)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpcore\_async\connection.py", line 124, in _connect
    stream = await self._network_backend.connect_tcp(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpcore\_backends\auto.py", line 31, in connect_tcp
    return await self._backend.connect_tcp(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpcore\_backends\anyio.py", line 113, in connect_tcp
    with map_exceptions(exc_map):
  File "C:\Program Files\Python311\Lib\contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpcore\_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectError: [Errno 11001] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\request\_httpxrequest.py", line 268, in do_request
    res = await self._client.request(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpx\_client.py", line 1530, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpx\_client.py", line 1617, in send
    response = await self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpx\_client.py", line 1645, in _send_handling_auth
    response = await self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpx\_client.py", line 1682, in _send_handling_redirects
    response = await self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpx\_client.py", line 1719, in _send_single_request
    response = await transport.handle_async_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpx\_transports\default.py", line 365, in handle_async_request
    with map_httpcore_exceptions():
  File "C:\Program Files\Python311\Lib\contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpx\_transports\default.py", line 83, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: [Errno 11001] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\ext\_updater.py", line 688, in _network_loop_retry
    if not await action_cb():
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\ext\_updater.py", line 384, in polling_action_cb
    raise exc
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\ext\_updater.py", line 373, in polling_action_cb
    updates = await self.bot.get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\ext\_extbot.py", line 558, in get_updates
    updates = await super().get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\_bot.py", line 525, in decorator
    result = await func(self, *args, **kwargs)  # skipcq: PYL-E1102
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\_bot.py", line 3584, in get_updates
    await self._post(
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\_bot.py", line 613, in _post
    return await self._do_post(
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\ext\_extbot.py", line 340, in _do_post
    return await super()._do_post(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\_bot.py", line 641, in _do_post
    return await request.post(
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\request\_baserequest.py", line 200, in post
    result = await self._request_wrapper(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\request\_baserequest.py", line 340, in _request_wrapper
    raise exc
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\request\_baserequest.py", line 330, in _request_wrapper
    code, payload = await self.do_request(
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\request\_httpxrequest.py", line 292, in do_request
    raise NetworkError(f"httpx.{err.__class__.__name__}: {err}") from err
telegram.error.NetworkError: httpx.ConnectError: [Errno 11001] getaddrinfo failed
2025-03-04 14:19:19,576 - telegram.ext.Updater - ERROR - Error while getting Updates: httpx.ConnectError: [Errno 11001] getaddrinfo failed
2025-03-04 14:19:19,576 - telegram.ext.Updater - ERROR - Exception happened while polling for updates.
Traceback (most recent call last):
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpx\_transports\default.py", line 66, in map_httpcore_exceptions
    yield
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpx\_transports\default.py", line 366, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 256, in handle_async_request
    raise exc from None
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 236, in handle_async_request
    response = await connection.handle_async_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpcore\_async\connection.py", line 101, in handle_async_request
    raise exc
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpcore\_async\connection.py", line 78, in handle_async_request
    stream = await self._connect(request)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpcore\_async\connection.py", line 124, in _connect
    stream = await self._network_backend.connect_tcp(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpcore\_backends\auto.py", line 31, in connect_tcp
    return await self._backend.connect_tcp(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpcore\_backends\anyio.py", line 113, in connect_tcp
    with map_exceptions(exc_map):
  File "C:\Program Files\Python311\Lib\contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpcore\_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectError: [Errno 11001] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\request\_httpxrequest.py", line 268, in do_request
    res = await self._client.request(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpx\_client.py", line 1530, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpx\_client.py", line 1617, in send
    response = await self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpx\_client.py", line 1645, in _send_handling_auth
    response = await self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpx\_client.py", line 1682, in _send_handling_redirects
    response = await self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpx\_client.py", line 1719, in _send_single_request
    response = await transport.handle_async_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpx\_transports\default.py", line 365, in handle_async_request
    with map_httpcore_exceptions():
  File "C:\Program Files\Python311\Lib\contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpx\_transports\default.py", line 83, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: [Errno 11001] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\ext\_updater.py", line 688, in _network_loop_retry
    if not await action_cb():
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\ext\_updater.py", line 384, in polling_action_cb
    raise exc
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\ext\_updater.py", line 373, in polling_action_cb
    updates = await self.bot.get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\ext\_extbot.py", line 558, in get_updates
    updates = await super().get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\_bot.py", line 525, in decorator
    result = await func(self, *args, **kwargs)  # skipcq: PYL-E1102
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\_bot.py", line 3584, in get_updates
    await self._post(
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\_bot.py", line 613, in _post
    return await self._do_post(
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\ext\_extbot.py", line 340, in _do_post
    return await super()._do_post(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\_bot.py", line 641, in _do_post
    return await request.post(
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\request\_baserequest.py", line 200, in post
    result = await self._request_wrapper(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\request\_baserequest.py", line 340, in _request_wrapper
    raise exc
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\request\_baserequest.py", line 330, in _request_wrapper
    code, payload = await self.do_request(
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\request\_httpxrequest.py", line 292, in do_request
    raise NetworkError(f"httpx.{err.__class__.__name__}: {err}") from err
telegram.error.NetworkError: httpx.ConnectError: [Errno 11001] getaddrinfo failed
2025-03-04 14:42:07,583 - telegram.ext.Updater - ERROR - Error while getting Updates: httpx.ConnectError: [Errno 11001] getaddrinfo failed
2025-03-04 14:42:07,593 - telegram.ext.Updater - ERROR - Exception happened while polling for updates.
Traceback (most recent call last):
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpx\_transports\default.py", line 66, in map_httpcore_exceptions
    yield
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpx\_transports\default.py", line 366, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 256, in handle_async_request
    raise exc from None
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 236, in handle_async_request
    response = await connection.handle_async_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpcore\_async\connection.py", line 101, in handle_async_request
    raise exc
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpcore\_async\connection.py", line 78, in handle_async_request
    stream = await self._connect(request)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpcore\_async\connection.py", line 124, in _connect
    stream = await self._network_backend.connect_tcp(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpcore\_backends\auto.py", line 31, in connect_tcp
    return await self._backend.connect_tcp(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpcore\_backends\anyio.py", line 113, in connect_tcp
    with map_exceptions(exc_map):
  File "C:\Program Files\Python311\Lib\contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpcore\_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectError: [Errno 11001] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\request\_httpxrequest.py", line 268, in do_request
    res = await self._client.request(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpx\_client.py", line 1530, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpx\_client.py", line 1617, in send
    response = await self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpx\_client.py", line 1645, in _send_handling_auth
    response = await self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpx\_client.py", line 1682, in _send_handling_redirects
    response = await self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpx\_client.py", line 1719, in _send_single_request
    response = await transport.handle_async_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpx\_transports\default.py", line 365, in handle_async_request
    with map_httpcore_exceptions():
  File "C:\Program Files\Python311\Lib\contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpx\_transports\default.py", line 83, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: [Errno 11001] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\ext\_updater.py", line 688, in _network_loop_retry
    if not await action_cb():
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\ext\_updater.py", line 384, in polling_action_cb
    raise exc
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\ext\_updater.py", line 373, in polling_action_cb
    updates = await self.bot.get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\ext\_extbot.py", line 558, in get_updates
    updates = await super().get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\_bot.py", line 525, in decorator
    result = await func(self, *args, **kwargs)  # skipcq: PYL-E1102
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\_bot.py", line 3584, in get_updates
    await self._post(
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\_bot.py", line 613, in _post
    return await self._do_post(
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\ext\_extbot.py", line 340, in _do_post
    return await super()._do_post(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\_bot.py", line 641, in _do_post
    return await request.post(
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\request\_baserequest.py", line 200, in post
    result = await self._request_wrapper(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\request\_baserequest.py", line 340, in _request_wrapper
    raise exc
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\request\_baserequest.py", line 330, in _request_wrapper
    code, payload = await self.do_request(
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\request\_httpxrequest.py", line 292, in do_request
    raise NetworkError(f"httpx.{err.__class__.__name__}: {err}") from err
telegram.error.NetworkError: httpx.ConnectError: [Errno 11001] getaddrinfo failed
2025-03-04 15:11:28,549 - telegram.ext.Updater - ERROR - Error while getting Updates: httpx.ConnectError: [Errno 11001] getaddrinfo failed
2025-03-04 15:11:28,551 - telegram.ext.Updater - ERROR - Exception happened while polling for updates.
Traceback (most recent call last):
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpx\_transports\default.py", line 66, in map_httpcore_exceptions
    yield
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpx\_transports\default.py", line 366, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 256, in handle_async_request
    raise exc from None
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 236, in handle_async_request
    response = await connection.handle_async_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpcore\_async\connection.py", line 101, in handle_async_request
    raise exc
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpcore\_async\connection.py", line 78, in handle_async_request
    stream = await self._connect(request)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpcore\_async\connection.py", line 124, in _connect
    stream = await self._network_backend.connect_tcp(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpcore\_backends\auto.py", line 31, in connect_tcp
    return await self._backend.connect_tcp(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpcore\_backends\anyio.py", line 113, in connect_tcp
    with map_exceptions(exc_map):
  File "C:\Program Files\Python311\Lib\contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpcore\_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectError: [Errno 11001] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\request\_httpxrequest.py", line 268, in do_request
    res = await self._client.request(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpx\_client.py", line 1530, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpx\_client.py", line 1617, in send
    response = await self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpx\_client.py", line 1645, in _send_handling_auth
    response = await self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpx\_client.py", line 1682, in _send_handling_redirects
    response = await self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpx\_client.py", line 1719, in _send_single_request
    response = await transport.handle_async_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpx\_transports\default.py", line 365, in handle_async_request
    with map_httpcore_exceptions():
  File "C:\Program Files\Python311\Lib\contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\httpx\_transports\default.py", line 83, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: [Errno 11001] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\ext\_updater.py", line 688, in _network_loop_retry
    if not await action_cb():
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\ext\_updater.py", line 384, in polling_action_cb
    raise exc
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\ext\_updater.py", line 373, in polling_action_cb
    updates = await self.bot.get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\ext\_extbot.py", line 558, in get_updates
    updates = await super().get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\_bot.py", line 525, in decorator
    result = await func(self, *args, **kwargs)  # skipcq: PYL-E1102
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\_bot.py", line 3584, in get_updates
    await self._post(
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\_bot.py", line 613, in _post
    return await self._do_post(
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\ext\_extbot.py", line 340, in _do_post
    return await super()._do_post(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\_bot.py", line 641, in _do_post
    return await request.post(
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\request\_baserequest.py", line 200, in post
    result = await self._request_wrapper(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\request\_baserequest.py", line 340, in _request_wrapper
    raise exc
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\request\_baserequest.py", line 330, in _request_wrapper
    code, payload = await self.do_request(
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\.venv\Lib\site-packages\telegram\request\_httpxrequest.py", line 292, in do_request
    raise NetworkError(f"httpx.{err.__class__.__name__}: {err}") from err
telegram.error.NetworkError: httpx.ConnectError: [Errno 11001] getaddrinfo failed
2025-03-04 15:21:42,366 - main - INFO - 환경변수 및 설정 초기화 중...
2025-03-04 15:21:42,367 - main - INFO - Bybit 테스트넷 클라이언트 초기화 중...
2025-03-04 15:21:42,377 - main - INFO - 서비스 초기화 중...
2025-03-04 15:21:42,377 - main - INFO - 마켓 데이터 서비스 중...
2025-03-04 15:21:43,687 - services.market_data_service - INFO - 마켓 데이터 로드 완료
2025-03-04 15:21:46,904 - telegram_bot.bot - INFO - 텔레그램 설정 로드:
2025-03-04 15:21:46,904 - telegram_bot.bot - INFO - - admin_chat_id: 583881676
2025-03-04 15:21:46,904 - telegram_bot.bot - INFO - - alert_chat_ids: [-1002464784986]
2025-03-04 15:21:47,326 - apscheduler.scheduler - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2025-03-04 15:21:47,326 - telegram_bot.bot - INFO - 봇 초기화 시작...
2025-03-04 15:21:47,326 - services.trade_history_service - INFO - === 포지션 정보 초기화 시작 ===
2025-03-04 15:21:47,326 - services.trade_history_service - INFO - 조회 기간: 2024-12-04 ~ 2025-03-04
2025-03-04 15:21:47,326 - services.trade_store - INFO - 날짜 범위 조회: 20241204 ~ 20250304
2025-03-04 15:21:47,326 - services.trade_store - INFO - 날짜: 20241204, 포지션 수: 0건
2025-03-04 15:21:47,326 - services.trade_store - INFO - 날짜: 20241205, 포지션 수: 0건
2025-03-04 15:21:47,326 - services.trade_store - INFO - 날짜: 20241206, 포지션 수: 0건
2025-03-04 15:21:47,326 - services.trade_store - INFO - 날짜: 20241207, 포지션 수: 0건
2025-03-04 15:21:47,326 - services.trade_store - INFO - 날짜: 20241208, 포지션 수: 0건
2025-03-04 15:21:47,326 - services.trade_store - INFO - 날짜: 20241209, 포지션 수: 0건
2025-03-04 15:21:47,326 - services.trade_store - INFO - 날짜: 20241210, 포지션 수: 0건
2025-03-04 15:21:47,326 - services.trade_store - INFO - 날짜: 20241211, 포지션 수: 0건
2025-03-04 15:21:47,326 - services.trade_store - INFO - 날짜: 20241212, 포지션 수: 0건
2025-03-04 15:21:47,326 - services.trade_store - INFO - 날짜: 20241213, 포지션 수: 0건
2025-03-04 15:21:47,326 - services.trade_store - INFO - 날짜: 20241214, 포지션 수: 0건
2025-03-04 15:21:47,326 - services.trade_store - INFO - 날짜: 20241215, 포지션 수: 0건
2025-03-04 15:21:47,326 - services.trade_store - INFO - 날짜: 20241216, 포지션 수: 0건
2025-03-04 15:21:47,326 - services.trade_store - INFO - 날짜: 20241217, 포지션 수: 0건
2025-03-04 15:21:47,326 - services.trade_store - INFO - 날짜: 20241218, 포지션 수: 0건
2025-03-04 15:21:47,326 - services.trade_store - INFO - 날짜: 20241219, 포지션 수: 0건
2025-03-04 15:21:47,326 - services.trade_store - INFO - 날짜: 20241220, 포지션 수: 0건
2025-03-04 15:21:47,326 - services.trade_store - INFO - 날짜: 20241221, 포지션 수: 0건
2025-03-04 15:21:47,326 - services.trade_store - INFO - 날짜: 20241222, 포지션 수: 0건
2025-03-04 15:21:47,326 - services.trade_store - INFO - 날짜: 20241223, 포지션 수: 0건
2025-03-04 15:21:47,326 - services.trade_store - INFO - 날짜: 20241224, 포지션 수: 0건
2025-03-04 15:21:47,326 - services.trade_store - INFO - 날짜: 20241225, 포지션 수: 0건
2025-03-04 15:21:47,326 - services.trade_store - INFO - 날짜: 20241226, 포지션 수: 0건
2025-03-04 15:21:47,326 - services.trade_store - INFO - 날짜: 20241227, 포지션 수: 0건
2025-03-04 15:21:47,326 - services.trade_store - INFO - 날짜: 20241228, 포지션 수: 0건
2025-03-04 15:21:47,326 - services.trade_store - INFO - 날짜: 20241229, 포지션 수: 0건
2025-03-04 15:21:47,338 - services.trade_store - INFO - 날짜: 20241230, 포지션 수: 0건
2025-03-04 15:21:47,338 - services.trade_store - INFO - 날짜: 20241231, 포지션 수: 0건
2025-03-04 15:21:47,339 - services.trade_store - INFO - 날짜: 20250101, 포지션 수: 0건
2025-03-04 15:21:47,339 - services.trade_store - INFO - 날짜: 20250102, 포지션 수: 0건
2025-03-04 15:21:47,339 - services.trade_store - INFO - 날짜: 20250103, 포지션 수: 0건
2025-03-04 15:21:47,339 - services.trade_store - INFO - 날짜: 20250104, 포지션 수: 0건
2025-03-04 15:21:47,339 - services.trade_store - INFO - 날짜: 20250105, 포지션 수: 0건
2025-03-04 15:21:47,340 - services.trade_store - INFO - 날짜: 20250106, 포지션 수: 0건
2025-03-04 15:21:47,340 - services.trade_store - INFO - 날짜: 20250107, 포지션 수: 0건
2025-03-04 15:21:47,340 - services.trade_store - INFO - 날짜: 20250108, 포지션 수: 0건
2025-03-04 15:21:47,340 - services.trade_store - INFO - 날짜: 20250109, 포지션 수: 0건
2025-03-04 15:21:47,340 - services.trade_store - INFO - 날짜: 20250110, 포지션 수: 0건
2025-03-04 15:21:47,340 - services.trade_store - INFO - 날짜: 20250111, 포지션 수: 0건
2025-03-04 15:21:47,340 - services.trade_store - INFO - 날짜: 20250112, 포지션 수: 0건
2025-03-04 15:21:47,341 - services.trade_store - INFO - 날짜: 20250113, 포지션 수: 0건
2025-03-04 15:21:47,341 - services.trade_store - INFO - 날짜: 20250114, 포지션 수: 0건
2025-03-04 15:21:47,341 - services.trade_store - INFO - 날짜: 20250115, 포지션 수: 0건
2025-03-04 15:21:47,341 - services.trade_store - INFO - 날짜: 20250116, 포지션 수: 0건
2025-03-04 15:21:47,342 - services.trade_store - INFO - 날짜: 20250117, 포지션 수: 0건
2025-03-04 15:21:47,342 - services.trade_store - INFO - 날짜: 20250118, 포지션 수: 0건
2025-03-04 15:21:47,342 - services.trade_store - INFO - 날짜: 20250119, 포지션 수: 0건
2025-03-04 15:21:47,342 - services.trade_store - INFO - 날짜: 20250120, 포지션 수: 0건
2025-03-04 15:21:47,342 - services.trade_store - INFO - 날짜: 20250121, 포지션 수: 0건
2025-03-04 15:21:47,342 - services.trade_store - INFO - 날짜: 20250122, 포지션 수: 0건
2025-03-04 15:21:47,343 - services.trade_store - INFO - 날짜: 20250123, 포지션 수: 0건
2025-03-04 15:21:47,343 - services.trade_store - INFO - 날짜: 20250124, 포지션 수: 0건
2025-03-04 15:21:47,343 - services.trade_store - INFO - 날짜: 20250125, 포지션 수: 0건
2025-03-04 15:21:47,343 - services.trade_store - INFO - 날짜: 20250126, 포지션 수: 0건
2025-03-04 15:21:47,343 - services.trade_store - INFO - 날짜: 20250127, 포지션 수: 0건
2025-03-04 15:21:47,343 - services.trade_store - INFO - 날짜: 20250128, 포지션 수: 0건
2025-03-04 15:21:47,343 - services.trade_store - INFO - 날짜: 20250129, 포지션 수: 0건
2025-03-04 15:21:47,343 - services.trade_store - INFO - 날짜: 20250130, 포지션 수: 0건
2025-03-04 15:21:47,344 - services.trade_store - INFO - 날짜: 20250131, 포지션 수: 0건
2025-03-04 15:21:47,344 - services.trade_store - INFO - 날짜: 20250201, 포지션 수: 0건
2025-03-04 15:21:47,344 - services.trade_store - INFO - 날짜: 20250202, 포지션 수: 0건
2025-03-04 15:21:47,344 - services.trade_store - INFO - 날짜: 20250203, 포지션 수: 0건
2025-03-04 15:21:47,344 - services.trade_store - INFO - 날짜: 20250204, 포지션 수: 0건
2025-03-04 15:21:47,344 - services.trade_store - INFO - 날짜: 20250205, 포지션 수: 0건
2025-03-04 15:21:47,344 - services.trade_store - INFO - 날짜: 20250206, 포지션 수: 0건
2025-03-04 15:21:47,344 - services.trade_store - INFO - 날짜: 20250207, 포지션 수: 0건
2025-03-04 15:21:47,344 - services.trade_store - INFO - 날짜: 20250208, 포지션 수: 0건
2025-03-04 15:21:47,345 - services.trade_store - INFO - 날짜: 20250209, 포지션 수: 0건
2025-03-04 15:21:47,345 - services.trade_store - INFO - 날짜: 20250210, 포지션 수: 0건
2025-03-04 15:21:47,345 - services.trade_store - INFO - 날짜: 20250211, 포지션 수: 0건
2025-03-04 15:21:47,345 - services.trade_store - INFO - 날짜: 20250212, 포지션 수: 0건
2025-03-04 15:21:47,345 - services.trade_store - INFO - 날짜: 20250213, 포지션 수: 0건
2025-03-04 15:21:47,345 - services.trade_store - INFO - 날짜: 20250214, 포지션 수: 0건
2025-03-04 15:21:47,345 - services.trade_store - INFO - 날짜: 20250215, 포지션 수: 0건
2025-03-04 15:21:47,345 - services.trade_store - INFO - 날짜: 20250216, 포지션 수: 0건
2025-03-04 15:21:47,346 - services.trade_store - INFO - 날짜: 20250217, 포지션 수: 0건
2025-03-04 15:21:47,346 - services.trade_store - INFO - 날짜: 20250218, 포지션 수: 0건
2025-03-04 15:21:47,346 - services.trade_store - INFO - 날짜: 20250219, 포지션 수: 0건
2025-03-04 15:21:47,346 - services.trade_store - INFO - 날짜: 20250220, 포지션 수: 0건
2025-03-04 15:21:47,346 - services.trade_store - INFO - 날짜: 20250221, 포지션 수: 0건
2025-03-04 15:21:47,346 - services.trade_store - INFO - 날짜: 20250222, 포지션 수: 0건
2025-03-04 15:21:47,346 - services.trade_store - INFO - 날짜: 20250223, 포지션 수: 0건
2025-03-04 15:21:47,346 - services.trade_store - INFO - 날짜: 20250224, 포지션 수: 0건
2025-03-04 15:21:47,347 - services.trade_store - INFO - 날짜: 20250225, 포지션 수: 0건
2025-03-04 15:21:47,347 - services.trade_store - INFO - 날짜: 20250226, 포지션 수: 0건
2025-03-04 15:21:47,347 - services.trade_store - INFO - 날짜: 20250227, 포지션 수: 0건
2025-03-04 15:21:47,347 - services.trade_store - INFO - 날짜: 20250228, 포지션 수: 0건
2025-03-04 15:21:47,347 - services.trade_store - INFO - 날짜: 20250301, 포지션 수: 0건
2025-03-04 15:21:47,347 - services.trade_store - INFO - 날짜: 20250302, 포지션 수: 0건
2025-03-04 15:21:47,347 - services.trade_store - INFO - 날짜: 20250303, 포지션 수: 0건
2025-03-04 15:21:47,348 - services.trade_store - INFO - 날짜: 20250304, 포지션 수: 0건
2025-03-04 15:21:47,348 - services.trade_store - INFO - 총 0건의 포지션 데이터 로드됨
2025-03-04 15:21:47,348 - services.trade_history_service - INFO - 기존 데이터: 0건
2025-03-04 15:21:47,348 - services.trade_history_service - INFO - 기존 데이터가 없습니다. 전체 기간 조회를 시작합니다.
2025-03-04 15:21:47,348 - services.trade_history_service - INFO - 기간별 조회: 2024-12-04 ~ 2024-12-11
2025-03-04 15:21:47,348 - services.trade_history_service - DEBUG - API 요청 파라미터: {'category': 'linear', 'symbol': 'BTCUSDT', 'startTime': '1733293307326', 'endTime': '1733898107326', 'limit': 100}
2025-03-04 15:21:47,473 - exchange.bybit_client - INFO - 서버 시간 동기화 완료: offset = 2394ms
2025-03-04 15:21:47,598 - services.trade_history_service - DEBUG - API 응답: {'retCode': 10004, 'retMsg': 'error sign! origin_string[1741069309868yjHTlVOB6X6Man1Ah520000category=linear&symbol=BTCUSDT&startTime=1733293307326&endTime=1733898107326&limit=100&timestamp=1741069309868]', 'result': {}, 'retExtInfo': {}, 'time': 1741069309996}
2025-03-04 15:21:48,611 - services.trade_history_service - INFO - 기간별 조회: 2024-12-11 ~ 2024-12-18
2025-03-04 15:21:48,611 - services.trade_history_service - DEBUG - API 요청 파라미터: {'category': 'linear', 'symbol': 'BTCUSDT', 'startTime': '1733898107326', 'endTime': '1734502907326', 'limit': 100}
2025-03-04 15:21:48,765 - services.trade_history_service - DEBUG - API 응답: {'retCode': 10004, 'retMsg': 'error sign! origin_string[1741069311005yjHTlVOB6X6Man1Ah520000category=linear&symbol=BTCUSDT&startTime=1733898107326&endTime=1734502907326&limit=100&timestamp=1741069311005]', 'result': {}, 'retExtInfo': {}, 'time': 1741069311161}
2025-03-04 15:21:49,772 - services.trade_history_service - INFO - 기간별 조회: 2024-12-18 ~ 2024-12-25
2025-03-04 15:21:49,773 - services.trade_history_service - DEBUG - API 요청 파라미터: {'category': 'linear', 'symbol': 'BTCUSDT', 'startTime': '1734502907326', 'endTime': '1735107707326', 'limit': 100}
2025-03-04 15:21:49,891 - services.trade_history_service - DEBUG - API 응답: {'retCode': 10004, 'retMsg': 'error sign! origin_string[1741069312167yjHTlVOB6X6Man1Ah520000category=linear&symbol=BTCUSDT&startTime=1734502907326&endTime=1735107707326&limit=100&timestamp=1741069312167]', 'result': {}, 'retExtInfo': {}, 'time': 1741069312299}
2025-03-04 15:21:50,907 - services.trade_history_service - INFO - 기간별 조회: 2024-12-25 ~ 2025-01-01
2025-03-04 15:21:50,907 - services.trade_history_service - DEBUG - API 요청 파라미터: {'category': 'linear', 'symbol': 'BTCUSDT', 'startTime': '1735107707326', 'endTime': '1735712507326', 'limit': 100}
2025-03-04 15:21:51,041 - services.trade_history_service - DEBUG - API 응답: {'retCode': 10004, 'retMsg': 'error sign! origin_string[1741069313301yjHTlVOB6X6Man1Ah520000category=linear&symbol=BTCUSDT&startTime=1735107707326&endTime=1735712507326&limit=100&timestamp=1741069313301]', 'result': {}, 'retExtInfo': {}, 'time': 1741069313441}
2025-03-04 15:21:52,062 - services.trade_history_service - INFO - 기간별 조회: 2025-01-01 ~ 2025-01-08
2025-03-04 15:21:52,062 - services.trade_history_service - DEBUG - API 요청 파라미터: {'category': 'linear', 'symbol': 'BTCUSDT', 'startTime': '1735712507326', 'endTime': '1736317307326', 'limit': 100}
2025-03-04 15:21:52,212 - services.trade_history_service - DEBUG - API 응답: {'retCode': 10004, 'retMsg': 'error sign! origin_string[1741069314456yjHTlVOB6X6Man1Ah520000category=linear&symbol=BTCUSDT&startTime=1735712507326&endTime=1736317307326&limit=100&timestamp=1741069314456]', 'result': {}, 'retExtInfo': {}, 'time': 1741069314610}
2025-03-04 15:21:53,214 - services.trade_history_service - INFO - 기간별 조회: 2025-01-08 ~ 2025-01-15
2025-03-04 15:21:53,219 - services.trade_history_service - DEBUG - API 요청 파라미터: {'category': 'linear', 'symbol': 'BTCUSDT', 'startTime': '1736317307326', 'endTime': '1736922107326', 'limit': 100}
2025-03-04 15:21:53,491 - services.trade_history_service - DEBUG - API 응답: {'retCode': 10004, 'retMsg': 'error sign! origin_string[1741069315613yjHTlVOB6X6Man1Ah520000category=linear&symbol=BTCUSDT&startTime=1736317307326&endTime=1736922107326&limit=100&timestamp=1741069315613]', 'result': {}, 'retExtInfo': {}, 'time': 1741069315883}
2025-03-04 15:21:54,491 - services.trade_history_service - INFO - 기간별 조회: 2025-01-15 ~ 2025-01-22
2025-03-04 15:21:54,491 - services.trade_history_service - DEBUG - API 요청 파라미터: {'category': 'linear', 'symbol': 'BTCUSDT', 'startTime': '1736922107326', 'endTime': '1737526907326', 'limit': 100}
2025-03-04 15:21:54,603 - services.trade_history_service - DEBUG - API 응답: {'retCode': 10004, 'retMsg': 'error sign! origin_string[1741069316885yjHTlVOB6X6Man1Ah520000category=linear&symbol=BTCUSDT&startTime=1736922107326&endTime=1737526907326&limit=100&timestamp=1741069316885]', 'result': {}, 'retExtInfo': {}, 'time': 1741069316997}
2025-03-04 15:21:55,609 - services.trade_history_service - INFO - 기간별 조회: 2025-01-22 ~ 2025-01-29
2025-03-04 15:21:55,609 - services.trade_history_service - DEBUG - API 요청 파라미터: {'category': 'linear', 'symbol': 'BTCUSDT', 'startTime': '1737526907326', 'endTime': '1738131707326', 'limit': 100}
2025-03-04 15:21:55,870 - services.trade_history_service - DEBUG - API 응답: {'retCode': 10004, 'retMsg': 'error sign! origin_string[1741069318003yjHTlVOB6X6Man1Ah520000category=linear&symbol=BTCUSDT&startTime=1737526907326&endTime=1738131707326&limit=100&timestamp=1741069318003]', 'result': {}, 'retExtInfo': {}, 'time': 1741069318263}
2025-03-04 15:21:56,882 - services.trade_history_service - INFO - 기간별 조회: 2025-01-29 ~ 2025-02-05
2025-03-04 15:21:56,883 - services.trade_history_service - DEBUG - API 요청 파라미터: {'category': 'linear', 'symbol': 'BTCUSDT', 'startTime': '1738131707326', 'endTime': '1738736507326', 'limit': 100}
2025-03-04 15:21:57,002 - services.trade_history_service - DEBUG - API 응답: {'retCode': 10004, 'retMsg': 'error sign! origin_string[1741069319279yjHTlVOB6X6Man1Ah520000category=linear&symbol=BTCUSDT&startTime=1738131707326&endTime=1738736507326&limit=100&timestamp=1741069319279]', 'result': {}, 'retExtInfo': {}, 'time': 1741069319408}
2025-03-04 15:21:58,004 - services.trade_history_service - INFO - 기간별 조회: 2025-02-05 ~ 2025-02-12
2025-03-04 15:21:58,004 - services.trade_history_service - DEBUG - API 요청 파라미터: {'category': 'linear', 'symbol': 'BTCUSDT', 'startTime': '1738736507326', 'endTime': '1739341307326', 'limit': 100}
2025-03-04 15:21:58,113 - services.trade_history_service - DEBUG - API 응답: {'retCode': 10004, 'retMsg': 'error sign! origin_string[1741069320398yjHTlVOB6X6Man1Ah520000category=linear&symbol=BTCUSDT&startTime=1738736507326&endTime=1739341307326&limit=100&timestamp=1741069320398]', 'result': {}, 'retExtInfo': {}, 'time': 1741069320506}
2025-03-04 15:21:59,123 - services.trade_history_service - INFO - 기간별 조회: 2025-02-12 ~ 2025-02-19
2025-03-04 15:21:59,123 - services.trade_history_service - DEBUG - API 요청 파라미터: {'category': 'linear', 'symbol': 'BTCUSDT', 'startTime': '1739341307326', 'endTime': '1739946107326', 'limit': 100}
2025-03-04 15:21:59,232 - services.trade_history_service - DEBUG - API 응답: {'retCode': 10004, 'retMsg': 'error sign! origin_string[1741069321518yjHTlVOB6X6Man1Ah520000category=linear&symbol=BTCUSDT&startTime=1739341307326&endTime=1739946107326&limit=100&timestamp=1741069321518]', 'result': {}, 'retExtInfo': {}, 'time': 1741069321637}
2025-03-04 15:22:00,235 - services.trade_history_service - INFO - 기간별 조회: 2025-02-19 ~ 2025-02-26
2025-03-04 15:22:00,235 - services.trade_history_service - DEBUG - API 요청 파라미터: {'category': 'linear', 'symbol': 'BTCUSDT', 'startTime': '1739946107326', 'endTime': '1740550907326', 'limit': 100}
2025-03-04 15:22:00,355 - services.trade_history_service - DEBUG - API 응답: {'retCode': 10004, 'retMsg': 'error sign! origin_string[1741069322629yjHTlVOB6X6Man1Ah520000category=linear&symbol=BTCUSDT&startTime=1739946107326&endTime=1740550907326&limit=100&timestamp=1741069322629]', 'result': {}, 'retExtInfo': {}, 'time': 1741069322754}
2025-03-04 15:22:01,355 - services.trade_history_service - INFO - 기간별 조회: 2025-02-26 ~ 2025-03-04
2025-03-04 15:22:01,355 - services.trade_history_service - DEBUG - API 요청 파라미터: {'category': 'linear', 'symbol': 'BTCUSDT', 'startTime': '1740550907326', 'endTime': '1741069307326', 'limit': 100}
2025-03-04 15:22:01,464 - services.trade_history_service - DEBUG - API 응답: {'retCode': 10004, 'retMsg': 'error sign! origin_string[1741069323750yjHTlVOB6X6Man1Ah520000category=linear&symbol=BTCUSDT&startTime=1740550907326&endTime=1741069307326&limit=100&timestamp=1741069323750]', 'result': {}, 'retExtInfo': {}, 'time': 1741069323860}
2025-03-04 15:22:02,474 - telegram_bot.bot - INFO - Application 빌드 시작...
2025-03-04 15:22:02,849 - apscheduler.scheduler - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2025-03-04 15:22:02,855 - telegram_bot.bot - INFO - 핸들러 초기화 완료
2025-03-04 15:22:02,855 - telegram_bot.bot - INFO - 봇 초기화 완료, 시작 준비 중...
2025-03-04 15:22:02,855 - telegram_bot.bot - INFO - 봇 시작 시도...
2025-03-04 15:22:02,856 - telegram_bot.bot - INFO - === 봇 시작 시도 ===
2025-03-04 15:22:03,940 - apscheduler.scheduler - INFO - Scheduler started
2025-03-04 15:22:03,940 - telegram.ext.Application - INFO - Application started
2025-03-04 15:22:04,206 - telegram_bot.bot - INFO - 🤖 바이빗 트레이딩 봇이 시작되었습니다
2025-03-04 15:37:16,710 - main - INFO - 환경변수 및 설정 초기화 중...
2025-03-04 15:37:16,711 - main - INFO - Bybit 테스트넷 클라이언트 초기화 중...
2025-03-04 15:37:16,716 - main - INFO - 서비스 초기화 중...
2025-03-04 15:37:16,716 - main - INFO - 마켓 데이터 서비스 중...
2025-03-04 15:37:18,331 - services.market_data_service - INFO - 마켓 데이터 로드 완료
2025-03-04 15:37:21,450 - telegram_bot.bot - INFO - 텔레그램 설정 로드:
2025-03-04 15:37:21,450 - telegram_bot.bot - INFO - - admin_chat_id: 583881676
2025-03-04 15:37:21,450 - telegram_bot.bot - INFO - - alert_chat_ids: [-1002464784986]
2025-03-04 15:37:21,848 - apscheduler.scheduler - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2025-03-04 15:37:21,848 - telegram_bot.bot - INFO - 봇 초기화 시작...
2025-03-04 15:37:21,848 - telegram_bot.bot - INFO - Application 빌드 시작...
2025-03-04 15:37:22,239 - apscheduler.scheduler - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2025-03-04 15:37:22,239 - telegram_bot.bot - INFO - 핸들러 초기화 완료
2025-03-04 15:37:22,239 - telegram_bot.bot - INFO - 봇 초기화 완료, 시작 준비 중...
2025-03-04 15:37:22,239 - telegram_bot.bot - INFO - 봇 시작 시도...
2025-03-04 15:37:22,239 - telegram_bot.bot - INFO - === 봇 시작 시도 ===
2025-03-04 15:37:22,249 - services.trade_history_service - INFO - === 포지션 정보 초기화 시작 ===
2025-03-04 15:37:22,249 - services.trade_store - INFO - 날짜 범위 조회: 20241204 ~ 20250304
2025-03-04 15:37:22,251 - services.trade_store - INFO - 날짜: 20241204, 포지션 수: 1건
2025-03-04 15:37:22,251 - services.trade_store - INFO - 날짜: 20241205, 포지션 수: 0건
2025-03-04 15:37:22,251 - services.trade_store - INFO - 날짜: 20241206, 포지션 수: 0건
2025-03-04 15:37:22,251 - services.trade_store - INFO - 날짜: 20241207, 포지션 수: 4건
2025-03-04 15:37:22,252 - services.trade_store - INFO - 날짜: 20241208, 포지션 수: 11건
2025-03-04 15:37:22,252 - services.trade_store - INFO - 날짜: 20241209, 포지션 수: 3건
2025-03-04 15:37:22,252 - services.trade_store - INFO - 날짜: 20241210, 포지션 수: 1건
2025-03-04 15:37:22,253 - services.trade_store - INFO - 날짜: 20241211, 포지션 수: 1건
2025-03-04 15:37:22,253 - services.trade_store - INFO - 날짜: 20241212, 포지션 수: 1건
2025-03-04 15:37:22,253 - services.trade_store - INFO - 날짜: 20241213, 포지션 수: 2건
2025-03-04 15:37:22,254 - services.trade_store - INFO - 날짜: 20241214, 포지션 수: 2건
2025-03-04 15:37:22,254 - services.trade_store - INFO - 날짜: 20241215, 포지션 수: 0건
2025-03-04 15:37:22,254 - services.trade_store - INFO - 날짜: 20241216, 포지션 수: 0건
2025-03-04 15:37:22,254 - services.trade_store - INFO - 날짜: 20241217, 포지션 수: 10건
2025-03-04 15:37:22,254 - services.trade_store - INFO - 날짜: 20241218, 포지션 수: 5건
2025-03-04 15:37:22,255 - services.trade_store - INFO - 날짜: 20241219, 포지션 수: 1건
2025-03-04 15:37:22,255 - services.trade_store - INFO - 날짜: 20241220, 포지션 수: 31건
2025-03-04 15:37:22,255 - services.trade_store - INFO - 날짜: 20241221, 포지션 수: 3건
2025-03-04 15:37:22,256 - services.trade_store - INFO - 날짜: 20241222, 포지션 수: 10건
2025-03-04 15:37:22,256 - services.trade_store - INFO - 날짜: 20241223, 포지션 수: 7건
2025-03-04 15:37:22,256 - services.trade_store - INFO - 날짜: 20241224, 포지션 수: 11건
2025-03-04 15:37:22,257 - services.trade_store - INFO - 날짜: 20241225, 포지션 수: 2건
2025-03-04 15:37:22,257 - services.trade_store - INFO - 날짜: 20241226, 포지션 수: 7건
2025-03-04 15:37:22,257 - services.trade_store - INFO - 날짜: 20241227, 포지션 수: 7건
2025-03-04 15:37:22,257 - services.trade_store - INFO - 날짜: 20241228, 포지션 수: 4건
2025-03-04 15:37:22,258 - services.trade_store - INFO - 날짜: 20241229, 포지션 수: 0건
2025-03-04 15:37:22,258 - services.trade_store - INFO - 날짜: 20241230, 포지션 수: 15건
2025-03-04 15:37:22,258 - services.trade_store - INFO - 날짜: 20241231, 포지션 수: 8건
2025-03-04 15:37:22,258 - services.trade_store - INFO - 날짜: 20250101, 포지션 수: 0건
2025-03-04 15:37:22,258 - services.trade_store - INFO - 날짜: 20250102, 포지션 수: 0건
2025-03-04 15:37:22,258 - services.trade_store - INFO - 날짜: 20250103, 포지션 수: 0건
2025-03-04 15:37:22,259 - services.trade_store - INFO - 날짜: 20250104, 포지션 수: 0건
2025-03-04 15:37:22,259 - services.trade_store - INFO - 날짜: 20250105, 포지션 수: 0건
2025-03-04 15:37:22,259 - services.trade_store - INFO - 날짜: 20250106, 포지션 수: 0건
2025-03-04 15:37:22,259 - services.trade_store - INFO - 날짜: 20250107, 포지션 수: 0건
2025-03-04 15:37:22,259 - services.trade_store - INFO - 날짜: 20250108, 포지션 수: 0건
2025-03-04 15:37:22,259 - services.trade_store - INFO - 날짜: 20250109, 포지션 수: 0건
2025-03-04 15:37:22,259 - services.trade_store - INFO - 날짜: 20250110, 포지션 수: 0건
2025-03-04 15:37:22,259 - services.trade_store - INFO - 날짜: 20250111, 포지션 수: 0건
2025-03-04 15:37:22,259 - services.trade_store - INFO - 날짜: 20250112, 포지션 수: 0건
2025-03-04 15:37:22,259 - services.trade_store - INFO - 날짜: 20250113, 포지션 수: 0건
2025-03-04 15:37:22,260 - services.trade_store - INFO - 날짜: 20250114, 포지션 수: 0건
2025-03-04 15:37:22,260 - services.trade_store - INFO - 날짜: 20250115, 포지션 수: 0건
2025-03-04 15:37:22,260 - services.trade_store - INFO - 날짜: 20250116, 포지션 수: 0건
2025-03-04 15:37:22,260 - services.trade_store - INFO - 날짜: 20250117, 포지션 수: 0건
2025-03-04 15:37:22,260 - services.trade_store - INFO - 날짜: 20250118, 포지션 수: 0건
2025-03-04 15:37:22,260 - services.trade_store - INFO - 날짜: 20250119, 포지션 수: 0건
2025-03-04 15:37:22,260 - services.trade_store - INFO - 날짜: 20250120, 포지션 수: 0건
2025-03-04 15:37:22,261 - services.trade_store - INFO - 날짜: 20250121, 포지션 수: 0건
2025-03-04 15:37:22,261 - services.trade_store - INFO - 날짜: 20250122, 포지션 수: 0건
2025-03-04 15:37:22,261 - services.trade_store - INFO - 날짜: 20250123, 포지션 수: 0건
2025-03-04 15:37:22,261 - services.trade_store - INFO - 날짜: 20250124, 포지션 수: 0건
2025-03-04 15:37:22,261 - services.trade_store - INFO - 날짜: 20250125, 포지션 수: 0건
2025-03-04 15:37:22,261 - services.trade_store - INFO - 날짜: 20250126, 포지션 수: 0건
2025-03-04 15:37:22,261 - services.trade_store - INFO - 날짜: 20250127, 포지션 수: 0건
2025-03-04 15:37:22,262 - services.trade_store - INFO - 날짜: 20250128, 포지션 수: 0건
2025-03-04 15:37:22,262 - services.trade_store - INFO - 날짜: 20250129, 포지션 수: 0건
2025-03-04 15:37:22,262 - services.trade_store - INFO - 날짜: 20250130, 포지션 수: 0건
2025-03-04 15:37:22,262 - services.trade_store - INFO - 날짜: 20250131, 포지션 수: 0건
2025-03-04 15:37:22,262 - services.trade_store - INFO - 날짜: 20250201, 포지션 수: 0건
2025-03-04 15:37:22,262 - services.trade_store - INFO - 날짜: 20250202, 포지션 수: 0건
2025-03-04 15:37:22,262 - services.trade_store - INFO - 날짜: 20250203, 포지션 수: 0건
2025-03-04 15:37:22,262 - services.trade_store - INFO - 날짜: 20250204, 포지션 수: 0건
2025-03-04 15:37:22,262 - services.trade_store - INFO - 날짜: 20250205, 포지션 수: 0건
2025-03-04 15:37:22,262 - services.trade_store - INFO - 날짜: 20250206, 포지션 수: 0건
2025-03-04 15:37:22,263 - services.trade_store - INFO - 날짜: 20250207, 포지션 수: 0건
2025-03-04 15:37:22,263 - services.trade_store - INFO - 날짜: 20250208, 포지션 수: 0건
2025-03-04 15:37:22,263 - services.trade_store - INFO - 날짜: 20250209, 포지션 수: 0건
2025-03-04 15:37:22,263 - services.trade_store - INFO - 날짜: 20250210, 포지션 수: 0건
2025-03-04 15:37:22,263 - services.trade_store - INFO - 날짜: 20250211, 포지션 수: 0건
2025-03-04 15:37:22,263 - services.trade_store - INFO - 날짜: 20250212, 포지션 수: 0건
2025-03-04 15:37:22,263 - services.trade_store - INFO - 날짜: 20250213, 포지션 수: 0건
2025-03-04 15:37:22,263 - services.trade_store - INFO - 날짜: 20250214, 포지션 수: 0건
2025-03-04 15:37:22,263 - services.trade_store - INFO - 날짜: 20250215, 포지션 수: 0건
2025-03-04 15:37:22,263 - services.trade_store - INFO - 날짜: 20250216, 포지션 수: 0건
2025-03-04 15:37:22,264 - services.trade_store - INFO - 날짜: 20250217, 포지션 수: 0건
2025-03-04 15:37:22,264 - services.trade_store - INFO - 날짜: 20250218, 포지션 수: 0건
2025-03-04 15:37:22,264 - services.trade_store - INFO - 날짜: 20250219, 포지션 수: 0건
2025-03-04 15:37:22,264 - services.trade_store - INFO - 날짜: 20250220, 포지션 수: 0건
2025-03-04 15:37:22,264 - services.trade_store - INFO - 날짜: 20250221, 포지션 수: 0건
2025-03-04 15:37:22,264 - services.trade_store - INFO - 날짜: 20250222, 포지션 수: 0건
2025-03-04 15:37:22,264 - services.trade_store - INFO - 날짜: 20250223, 포지션 수: 0건
2025-03-04 15:37:22,264 - services.trade_store - INFO - 날짜: 20250224, 포지션 수: 0건
2025-03-04 15:37:22,264 - services.trade_store - INFO - 날짜: 20250225, 포지션 수: 0건
2025-03-04 15:37:22,265 - services.trade_store - INFO - 날짜: 20250226, 포지션 수: 0건
2025-03-04 15:37:22,265 - services.trade_store - INFO - 날짜: 20250227, 포지션 수: 0건
2025-03-04 15:37:22,265 - services.trade_store - INFO - 날짜: 20250228, 포지션 수: 0건
2025-03-04 15:37:22,265 - services.trade_store - INFO - 날짜: 20250301, 포지션 수: 0건
2025-03-04 15:37:22,265 - services.trade_store - INFO - 날짜: 20250302, 포지션 수: 0건
2025-03-04 15:37:22,266 - services.trade_store - INFO - 날짜: 20250303, 포지션 수: 0건
2025-03-04 15:37:22,266 - services.trade_store - INFO - 날짜: 20250304, 포지션 수: 0건
2025-03-04 15:37:22,266 - services.trade_store - INFO - 총 147건의 포지션 데이터 로드됨
2025-03-04 15:37:22,266 - services.trade_history_service - INFO - 마지막 업데이트 정보가 없습니다. 전체 기간 조회를 시작합니다.
2025-03-04 15:37:22,266 - services.trade_history_service - INFO - 기간별 조회: 2024-12-04 ~ 2024-12-11
2025-03-04 15:37:22,400 - exchange.bybit_client - INFO - 서버 시간 동기화 완료: offset = 2394ms
2025-03-04 15:37:22,501 - exchange.bybit_client - ERROR - API 요청 실패: Cannot connect to host api-testnet.bybit.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')]
2025-03-04 15:37:23,525 - services.trade_history_service - INFO - 기간별 조회: 2024-12-11 ~ 2024-12-18
2025-03-04 15:37:23,619 - apscheduler.scheduler - INFO - Scheduler started
2025-03-04 15:37:23,619 - telegram.ext.Application - INFO - Application started
2025-03-04 15:37:23,632 - exchange.bybit_client - ERROR - API 요청 실패: Cannot connect to host api-testnet.bybit.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')]
2025-03-04 15:37:23,876 - telegram_bot.bot - INFO - 🤖 바이빗 트레이딩 봇이 시작되었습니다
2025-03-04 15:37:24,641 - services.trade_history_service - INFO - 기간별 조회: 2024-12-18 ~ 2024-12-25
2025-03-04 15:37:24,759 - exchange.bybit_client - ERROR - API 요청 실패: Cannot connect to host api-testnet.bybit.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')]
2025-03-04 15:37:25,760 - services.trade_history_service - INFO - 기간별 조회: 2024-12-25 ~ 2025-01-01
2025-03-04 15:37:26,100 - exchange.bybit_client - ERROR - API 요청 실패: Cannot connect to host api-testnet.bybit.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')]
2025-03-04 15:37:27,104 - services.trade_history_service - INFO - 기간별 조회: 2025-01-01 ~ 2025-01-08
2025-03-04 15:37:27,174 - exchange.bybit_client - ERROR - API 요청 실패: Cannot connect to host api-testnet.bybit.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')]
2025-03-04 15:37:28,185 - services.trade_history_service - INFO - 기간별 조회: 2025-01-08 ~ 2025-01-15
2025-03-04 15:37:28,298 - exchange.bybit_client - ERROR - API 요청 실패: Cannot connect to host api-testnet.bybit.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')]
2025-03-04 15:37:29,302 - services.trade_history_service - INFO - 기간별 조회: 2025-01-15 ~ 2025-01-22
2025-03-04 15:37:29,371 - exchange.bybit_client - ERROR - API 요청 실패: Cannot connect to host api-testnet.bybit.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')]
2025-03-04 15:37:30,372 - services.trade_history_service - INFO - 기간별 조회: 2025-01-22 ~ 2025-01-29
2025-03-04 15:37:30,450 - exchange.bybit_client - ERROR - API 요청 실패: Cannot connect to host api-testnet.bybit.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')]
2025-03-04 15:37:31,454 - services.trade_history_service - INFO - 기간별 조회: 2025-01-29 ~ 2025-02-05
2025-03-04 15:37:31,538 - exchange.bybit_client - ERROR - API 요청 실패: Cannot connect to host api-testnet.bybit.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')]
2025-03-04 15:37:32,551 - services.trade_history_service - INFO - 기간별 조회: 2025-02-05 ~ 2025-02-12
2025-03-04 15:37:32,635 - exchange.bybit_client - ERROR - API 요청 실패: Cannot connect to host api-testnet.bybit.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')]
2025-03-04 15:37:33,637 - services.trade_history_service - INFO - 기간별 조회: 2025-02-12 ~ 2025-02-19
2025-03-04 15:37:33,746 - exchange.bybit_client - ERROR - API 요청 실패: Cannot connect to host api-testnet.bybit.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')]
2025-03-04 15:37:34,743 - services.trade_history_service - INFO - 기간별 조회: 2025-02-19 ~ 2025-02-26
2025-03-04 15:37:34,835 - exchange.bybit_client - ERROR - API 요청 실패: Cannot connect to host api-testnet.bybit.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')]
2025-03-04 15:37:35,849 - services.trade_history_service - INFO - 기간별 조회: 2025-02-26 ~ 2025-03-04
2025-03-04 15:37:35,965 - exchange.bybit_client - ERROR - API 요청 실패: Cannot connect to host api-testnet.bybit.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')]
2025-03-04 15:49:16,407 - main - INFO - 환경변수 및 설정 초기화 중...
2025-03-04 15:49:16,407 - main - INFO - Bybit 테스트넷 클라이언트 초기화 중...
2025-03-04 15:49:16,604 - main - ERROR - 실행 중 에러 발생: 'dict' object has no attribute 'verify'
2025-03-04 15:49:16,614 - main - ERROR - Traceback (most recent call last):
  File "C:\Users\oasis\Aibybit_2\src\main.py", line 60, in main
    bybit_client = BybitClient(config=bybit_config)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oasis\Aibybit_2\src\exchange\bybit_client.py", line 52, in __init__
    self.exchange.session.verify = certifi.where()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'verify'

2025-03-04 15:49:16,614 - ccxt.base.exchange - WARNING - bybit requires to release all resources with an explicit call to the .close() coroutine. If you are using the exchange instance with async coroutines, add `await exchange.close()` to your code into a place when you're done with the exchange and don't need the exchange instance anymore (at the end of your async coroutine).
2025-03-04 15:54:23,605 - main - INFO - 환경변수 및 설정 초기화 중...
2025-03-04 15:54:23,605 - main - INFO - Bybit 테스트넷 클라이언트 초기화 중...
2025-03-04 15:54:23,813 - main - INFO - 서비스 초기화 중...
2025-03-04 15:54:23,813 - main - INFO - 마켓 데이터 서비스 중...
2025-03-04 15:54:25,383 - services.market_data_service - INFO - 마켓 데이터 로드 완료
2025-03-04 15:54:25,617 - telegram_bot.bot - INFO - 텔레그램 설정 로드:
2025-03-04 15:54:25,619 - telegram_bot.bot - INFO - - admin_chat_id: 583881676
2025-03-04 15:54:25,619 - telegram_bot.bot - INFO - - alert_chat_ids: [-1002464784986]
2025-03-04 15:54:26,013 - apscheduler.scheduler - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2025-03-04 15:54:26,013 - telegram_bot.bot - INFO - 봇 초기화 시작...
2025-03-04 15:54:26,013 - services.trade_history_service - INFO - === 포지션 정보 초기화 시작 ===
2025-03-04 15:54:26,013 - services.trade_history_service - INFO - 조회 기간: 2024-12-04 ~ 2025-03-04
2025-03-04 15:54:26,013 - services.trade_store - INFO - 날짜 범위 조회: 20241204 ~ 20250304
2025-03-04 15:54:26,013 - services.trade_store - INFO - 날짜: 20241204, 포지션 수: 0건
2025-03-04 15:54:26,013 - services.trade_store - INFO - 날짜: 20241205, 포지션 수: 0건
2025-03-04 15:54:26,013 - services.trade_store - INFO - 날짜: 20241206, 포지션 수: 0건
2025-03-04 15:54:26,013 - services.trade_store - INFO - 날짜: 20241207, 포지션 수: 0건
2025-03-04 15:54:26,013 - services.trade_store - INFO - 날짜: 20241208, 포지션 수: 0건
2025-03-04 15:54:26,013 - services.trade_store - INFO - 날짜: 20241209, 포지션 수: 0건
2025-03-04 15:54:26,013 - services.trade_store - INFO - 날짜: 20241210, 포지션 수: 0건
2025-03-04 15:54:26,013 - services.trade_store - INFO - 날짜: 20241211, 포지션 수: 0건
2025-03-04 15:54:26,013 - services.trade_store - INFO - 날짜: 20241212, 포지션 수: 0건
2025-03-04 15:54:26,013 - services.trade_store - INFO - 날짜: 20241213, 포지션 수: 0건
2025-03-04 15:54:26,013 - services.trade_store - INFO - 날짜: 20241214, 포지션 수: 0건
2025-03-04 15:54:26,013 - services.trade_store - INFO - 날짜: 20241215, 포지션 수: 0건
2025-03-04 15:54:26,013 - services.trade_store - INFO - 날짜: 20241216, 포지션 수: 0건
2025-03-04 15:54:26,013 - services.trade_store - INFO - 날짜: 20241217, 포지션 수: 0건
2025-03-04 15:54:26,020 - services.trade_store - INFO - 날짜: 20241218, 포지션 수: 0건
2025-03-04 15:54:26,020 - services.trade_store - INFO - 날짜: 20241219, 포지션 수: 0건
2025-03-04 15:54:26,020 - services.trade_store - INFO - 날짜: 20241220, 포지션 수: 0건
2025-03-04 15:54:26,020 - services.trade_store - INFO - 날짜: 20241221, 포지션 수: 0건
2025-03-04 15:54:26,020 - services.trade_store - INFO - 날짜: 20241222, 포지션 수: 0건
2025-03-04 15:54:26,020 - services.trade_store - INFO - 날짜: 20241223, 포지션 수: 0건
2025-03-04 15:54:26,020 - services.trade_store - INFO - 날짜: 20241224, 포지션 수: 0건
2025-03-04 15:54:26,021 - services.trade_store - INFO - 날짜: 20241225, 포지션 수: 0건
2025-03-04 15:54:26,021 - services.trade_store - INFO - 날짜: 20241226, 포지션 수: 0건
2025-03-04 15:54:26,021 - services.trade_store - INFO - 날짜: 20241227, 포지션 수: 0건
2025-03-04 15:54:26,021 - services.trade_store - INFO - 날짜: 20241228, 포지션 수: 0건
2025-03-04 15:54:26,021 - services.trade_store - INFO - 날짜: 20241229, 포지션 수: 0건
2025-03-04 15:54:26,021 - services.trade_store - INFO - 날짜: 20241230, 포지션 수: 0건
2025-03-04 15:54:26,021 - services.trade_store - INFO - 날짜: 20241231, 포지션 수: 0건
2025-03-04 15:54:26,022 - services.trade_store - INFO - 날짜: 20250101, 포지션 수: 0건
2025-03-04 15:54:26,022 - services.trade_store - INFO - 날짜: 20250102, 포지션 수: 0건
2025-03-04 15:54:26,022 - services.trade_store - INFO - 날짜: 20250103, 포지션 수: 0건
2025-03-04 15:54:26,022 - services.trade_store - INFO - 날짜: 20250104, 포지션 수: 0건
2025-03-04 15:54:26,022 - services.trade_store - INFO - 날짜: 20250105, 포지션 수: 0건
2025-03-04 15:54:26,022 - services.trade_store - INFO - 날짜: 20250106, 포지션 수: 0건
2025-03-04 15:54:26,023 - services.trade_store - INFO - 날짜: 20250107, 포지션 수: 0건
2025-03-04 15:54:26,023 - services.trade_store - INFO - 날짜: 20250108, 포지션 수: 0건
2025-03-04 15:54:26,023 - services.trade_store - INFO - 날짜: 20250109, 포지션 수: 0건
2025-03-04 15:54:26,023 - services.trade_store - INFO - 날짜: 20250110, 포지션 수: 0건
2025-03-04 15:54:26,023 - services.trade_store - INFO - 날짜: 20250111, 포지션 수: 0건
2025-03-04 15:54:26,023 - services.trade_store - INFO - 날짜: 20250112, 포지션 수: 0건
2025-03-04 15:54:26,023 - services.trade_store - INFO - 날짜: 20250113, 포지션 수: 0건
2025-03-04 15:54:26,024 - services.trade_store - INFO - 날짜: 20250114, 포지션 수: 0건
2025-03-04 15:54:26,024 - services.trade_store - INFO - 날짜: 20250115, 포지션 수: 0건
2025-03-04 15:54:26,024 - services.trade_store - INFO - 날짜: 20250116, 포지션 수: 0건
2025-03-04 15:54:26,024 - services.trade_store - INFO - 날짜: 20250117, 포지션 수: 0건
2025-03-04 15:54:26,024 - services.trade_store - INFO - 날짜: 20250118, 포지션 수: 0건
2025-03-04 15:54:26,024 - services.trade_store - INFO - 날짜: 20250119, 포지션 수: 0건
2025-03-04 15:54:26,024 - services.trade_store - INFO - 날짜: 20250120, 포지션 수: 0건
2025-03-04 15:54:26,024 - services.trade_store - INFO - 날짜: 20250121, 포지션 수: 0건
2025-03-04 15:54:26,025 - services.trade_store - INFO - 날짜: 20250122, 포지션 수: 0건
2025-03-04 15:54:26,025 - services.trade_store - INFO - 날짜: 20250123, 포지션 수: 0건
2025-03-04 15:54:26,025 - services.trade_store - INFO - 날짜: 20250124, 포지션 수: 0건
2025-03-04 15:54:26,025 - services.trade_store - INFO - 날짜: 20250125, 포지션 수: 0건
2025-03-04 15:54:26,025 - services.trade_store - INFO - 날짜: 20250126, 포지션 수: 0건
2025-03-04 15:54:26,025 - services.trade_store - INFO - 날짜: 20250127, 포지션 수: 0건
2025-03-04 15:54:26,025 - services.trade_store - INFO - 날짜: 20250128, 포지션 수: 0건
2025-03-04 15:54:26,025 - services.trade_store - INFO - 날짜: 20250129, 포지션 수: 0건
2025-03-04 15:54:26,025 - services.trade_store - INFO - 날짜: 20250130, 포지션 수: 0건
2025-03-04 15:54:26,025 - services.trade_store - INFO - 날짜: 20250131, 포지션 수: 0건
2025-03-04 15:54:26,025 - services.trade_store - INFO - 날짜: 20250201, 포지션 수: 0건
2025-03-04 15:54:26,026 - services.trade_store - INFO - 날짜: 20250202, 포지션 수: 0건
2025-03-04 15:54:26,026 - services.trade_store - INFO - 날짜: 20250203, 포지션 수: 0건
2025-03-04 15:54:26,026 - services.trade_store - INFO - 날짜: 20250204, 포지션 수: 0건
2025-03-04 15:54:26,026 - services.trade_store - INFO - 날짜: 20250205, 포지션 수: 0건
2025-03-04 15:54:26,026 - services.trade_store - INFO - 날짜: 20250206, 포지션 수: 0건
2025-03-04 15:54:26,026 - services.trade_store - INFO - 날짜: 20250207, 포지션 수: 0건
2025-03-04 15:54:26,026 - services.trade_store - INFO - 날짜: 20250208, 포지션 수: 0건
2025-03-04 15:54:26,026 - services.trade_store - INFO - 날짜: 20250209, 포지션 수: 0건
2025-03-04 15:54:26,027 - services.trade_store - INFO - 날짜: 20250210, 포지션 수: 0건
2025-03-04 15:54:26,027 - services.trade_store - INFO - 날짜: 20250211, 포지션 수: 0건
2025-03-04 15:54:26,027 - services.trade_store - INFO - 날짜: 20250212, 포지션 수: 0건
2025-03-04 15:54:26,027 - services.trade_store - INFO - 날짜: 20250213, 포지션 수: 0건
2025-03-04 15:54:26,027 - services.trade_store - INFO - 날짜: 20250214, 포지션 수: 0건
2025-03-04 15:54:26,027 - services.trade_store - INFO - 날짜: 20250215, 포지션 수: 0건
2025-03-04 15:54:26,027 - services.trade_store - INFO - 날짜: 20250216, 포지션 수: 0건
2025-03-04 15:54:26,028 - services.trade_store - INFO - 날짜: 20250217, 포지션 수: 0건
2025-03-04 15:54:26,028 - services.trade_store - INFO - 날짜: 20250218, 포지션 수: 0건
2025-03-04 15:54:26,028 - services.trade_store - INFO - 날짜: 20250219, 포지션 수: 0건
2025-03-04 15:54:26,028 - services.trade_store - INFO - 날짜: 20250220, 포지션 수: 0건
2025-03-04 15:54:26,028 - services.trade_store - INFO - 날짜: 20250221, 포지션 수: 0건
2025-03-04 15:54:26,028 - services.trade_store - INFO - 날짜: 20250222, 포지션 수: 0건
2025-03-04 15:54:26,028 - services.trade_store - INFO - 날짜: 20250223, 포지션 수: 0건
2025-03-04 15:54:26,028 - services.trade_store - INFO - 날짜: 20250224, 포지션 수: 0건
2025-03-04 15:54:26,028 - services.trade_store - INFO - 날짜: 20250225, 포지션 수: 0건
2025-03-04 15:54:26,029 - services.trade_store - INFO - 날짜: 20250226, 포지션 수: 0건
2025-03-04 15:54:26,029 - services.trade_store - INFO - 날짜: 20250227, 포지션 수: 0건
2025-03-04 15:54:26,029 - services.trade_store - INFO - 날짜: 20250228, 포지션 수: 0건
2025-03-04 15:54:26,029 - services.trade_store - INFO - 날짜: 20250301, 포지션 수: 0건
2025-03-04 15:54:26,029 - services.trade_store - INFO - 날짜: 20250302, 포지션 수: 0건
2025-03-04 15:54:26,029 - services.trade_store - INFO - 날짜: 20250303, 포지션 수: 0건
2025-03-04 15:54:26,029 - services.trade_store - INFO - 날짜: 20250304, 포지션 수: 0건
2025-03-04 15:54:26,029 - services.trade_store - INFO - 총 0건의 포지션 데이터 로드됨
2025-03-04 15:54:26,029 - services.trade_history_service - INFO - 기존 데이터: 0건
2025-03-04 15:54:26,029 - services.trade_history_service - INFO - 기존 데이터가 없습니다. 전체 기간 조회를 시작합니다.
2025-03-04 15:54:26,029 - services.trade_history_service - INFO - 기간별 조회: 2024-12-04 ~ 2024-12-11
2025-03-04 15:54:26,030 - services.trade_history_service - DEBUG - API 요청 파라미터: {'category': 'linear', 'symbol': 'BTCUSDT', 'startTime': '1733295266013', 'endTime': '1733900066013', 'limit': 100}
2025-03-04 15:54:26,152 - exchange.bybit_client - INFO - 서버 시간 동기화 완료: offset = -9ms
2025-03-04 15:54:26,420 - services.trade_history_service - DEBUG - API 응답: {'retCode': 10004, 'retMsg': 'error sign! origin_string[1741071266144yjHTlVOB6X6Man1Ah55000category=linear&symbol=BTCUSDT&startTime=1733295266013&endTime=1733900066013&limit=100&timestamp=1741071266144]', 'result': {}, 'retExtInfo': {}, 'time': 1741071266413}
2025-03-04 15:54:27,434 - services.trade_history_service - INFO - 기간별 조회: 2024-12-11 ~ 2024-12-18
2025-03-04 15:54:27,434 - services.trade_history_service - DEBUG - API 요청 파라미터: {'category': 'linear', 'symbol': 'BTCUSDT', 'startTime': '1733900066013', 'endTime': '1734504866013', 'limit': 100}
2025-03-04 15:54:27,696 - services.trade_history_service - DEBUG - API 응답: {'retCode': 10004, 'retMsg': 'error sign! origin_string[1741071267425yjHTlVOB6X6Man1Ah55000category=linear&symbol=BTCUSDT&startTime=1733900066013&endTime=1734504866013&limit=100&timestamp=1741071267425]', 'result': {}, 'retExtInfo': {}, 'time': 1741071267687}
2025-03-04 15:54:28,694 - services.trade_history_service - INFO - 기간별 조회: 2024-12-18 ~ 2024-12-25
2025-03-04 15:54:28,695 - services.trade_history_service - DEBUG - API 요청 파라미터: {'category': 'linear', 'symbol': 'BTCUSDT', 'startTime': '1734504866013', 'endTime': '1735109666013', 'limit': 100}
2025-03-04 15:54:28,804 - services.trade_history_service - DEBUG - API 응답: {'retCode': 10004, 'retMsg': 'error sign! origin_string[1741071268686yjHTlVOB6X6Man1Ah55000category=linear&symbol=BTCUSDT&startTime=1734504866013&endTime=1735109666013&limit=100&timestamp=1741071268686]', 'result': {}, 'retExtInfo': {}, 'time': 1741071268807}
2025-03-04 15:54:29,804 - services.trade_history_service - INFO - 기간별 조회: 2024-12-25 ~ 2025-01-01
2025-03-04 15:54:29,805 - services.trade_history_service - DEBUG - API 요청 파라미터: {'category': 'linear', 'symbol': 'BTCUSDT', 'startTime': '1735109666013', 'endTime': '1735714466013', 'limit': 100}
2025-03-04 15:54:29,933 - services.trade_history_service - DEBUG - API 응답: {'retCode': 10004, 'retMsg': 'error sign! origin_string[1741071269796yjHTlVOB6X6Man1Ah55000category=linear&symbol=BTCUSDT&startTime=1735109666013&endTime=1735714466013&limit=100&timestamp=1741071269796]', 'result': {}, 'retExtInfo': {}, 'time': 1741071269927}
2025-03-04 15:54:30,937 - services.trade_history_service - INFO - 기간별 조회: 2025-01-01 ~ 2025-01-08
2025-03-04 15:54:30,937 - services.trade_history_service - DEBUG - API 요청 파라미터: {'category': 'linear', 'symbol': 'BTCUSDT', 'startTime': '1735714466013', 'endTime': '1736319266013', 'limit': 100}
2025-03-04 15:54:32,049 - services.trade_history_service - DEBUG - API 응답: {'retCode': 10004, 'retMsg': 'error sign! origin_string[1741071270928yjHTlVOB6X6Man1Ah55000category=linear&symbol=BTCUSDT&startTime=1735714466013&endTime=1736319266013&limit=100&timestamp=1741071270928]', 'result': {}, 'retExtInfo': {}, 'time': 1741071272041}
2025-03-04 15:54:33,062 - services.trade_history_service - INFO - 기간별 조회: 2025-01-08 ~ 2025-01-15
2025-03-04 15:54:33,063 - services.trade_history_service - DEBUG - API 요청 파라미터: {'category': 'linear', 'symbol': 'BTCUSDT', 'startTime': '1736319266013', 'endTime': '1736924066013', 'limit': 100}
2025-03-04 15:54:33,182 - services.trade_history_service - DEBUG - API 응답: {'retCode': 10004, 'retMsg': 'error sign! origin_string[1741071273055yjHTlVOB6X6Man1Ah55000category=linear&symbol=BTCUSDT&startTime=1736319266013&endTime=1736924066013&limit=100&timestamp=1741071273055]', 'result': {}, 'retExtInfo': {}, 'time': 1741071273173}
2025-03-04 15:54:34,192 - services.trade_history_service - INFO - 기간별 조회: 2025-01-15 ~ 2025-01-22
2025-03-04 15:54:34,192 - services.trade_history_service - DEBUG - API 요청 파라미터: {'category': 'linear', 'symbol': 'BTCUSDT', 'startTime': '1736924066013', 'endTime': '1737528866013', 'limit': 100}
2025-03-04 15:54:34,326 - services.trade_history_service - DEBUG - API 응답: {'retCode': 10004, 'retMsg': 'error sign! origin_string[1741071274184yjHTlVOB6X6Man1Ah55000category=linear&symbol=BTCUSDT&startTime=1736924066013&endTime=1737528866013&limit=100&timestamp=1741071274184]', 'result': {}, 'retExtInfo': {}, 'time': 1741071274332}
2025-03-04 15:54:35,342 - services.trade_history_service - INFO - 기간별 조회: 2025-01-22 ~ 2025-01-29
2025-03-04 15:54:35,342 - services.trade_history_service - DEBUG - API 요청 파라미터: {'category': 'linear', 'symbol': 'BTCUSDT', 'startTime': '1737528866013', 'endTime': '1738133666013', 'limit': 100}
2025-03-04 15:54:35,444 - services.trade_history_service - DEBUG - API 응답: {'retCode': 10004, 'retMsg': 'error sign! origin_string[1741071275333yjHTlVOB6X6Man1Ah55000category=linear&symbol=BTCUSDT&startTime=1737528866013&endTime=1738133666013&limit=100&timestamp=1741071275333]', 'result': {}, 'retExtInfo': {}, 'time': 1741071275448}
2025-03-04 15:54:36,449 - services.trade_history_service - INFO - 기간별 조회: 2025-01-29 ~ 2025-02-05
2025-03-04 15:54:36,449 - services.trade_history_service - DEBUG - API 요청 파라미터: {'category': 'linear', 'symbol': 'BTCUSDT', 'startTime': '1738133666013', 'endTime': '1738738466013', 'limit': 100}
2025-03-04 15:54:36,719 - services.trade_history_service - DEBUG - API 응답: {'retCode': 10004, 'retMsg': 'error sign! origin_string[1741071276441yjHTlVOB6X6Man1Ah55000category=linear&symbol=BTCUSDT&startTime=1738133666013&endTime=1738738466013&limit=100&timestamp=1741071276441]', 'result': {}, 'retExtInfo': {}, 'time': 1741071276708}
2025-03-04 15:54:37,714 - services.trade_history_service - INFO - 기간별 조회: 2025-02-05 ~ 2025-02-12
2025-03-04 15:54:37,715 - services.trade_history_service - DEBUG - API 요청 파라미터: {'category': 'linear', 'symbol': 'BTCUSDT', 'startTime': '1738738466013', 'endTime': '1739343266013', 'limit': 100}
2025-03-04 15:54:37,816 - services.trade_history_service - DEBUG - API 응답: {'retCode': 10004, 'retMsg': 'error sign! origin_string[1741071277706yjHTlVOB6X6Man1Ah55000category=linear&symbol=BTCUSDT&startTime=1738738466013&endTime=1739343266013&limit=100&timestamp=1741071277706]', 'result': {}, 'retExtInfo': {}, 'time': 1741071277817}
2025-03-04 15:54:38,843 - services.trade_history_service - INFO - 기간별 조회: 2025-02-12 ~ 2025-02-19
2025-03-04 15:54:38,843 - services.trade_history_service - DEBUG - API 요청 파라미터: {'category': 'linear', 'symbol': 'BTCUSDT', 'startTime': '1739343266013', 'endTime': '1739948066013', 'limit': 100}
2025-03-04 15:54:38,958 - services.trade_history_service - DEBUG - API 응답: {'retCode': 10004, 'retMsg': 'error sign! origin_string[1741071278834yjHTlVOB6X6Man1Ah55000category=linear&symbol=BTCUSDT&startTime=1739343266013&endTime=1739948066013&limit=100&timestamp=1741071278834]', 'result': {}, 'retExtInfo': {}, 'time': 1741071278949}
2025-03-04 15:54:39,978 - services.trade_history_service - INFO - 기간별 조회: 2025-02-19 ~ 2025-02-26
2025-03-04 15:54:39,979 - services.trade_history_service - DEBUG - API 요청 파라미터: {'category': 'linear', 'symbol': 'BTCUSDT', 'startTime': '1739948066013', 'endTime': '1740552866013', 'limit': 100}
2025-03-04 15:54:40,096 - services.trade_history_service - DEBUG - API 응답: {'retCode': 10004, 'retMsg': 'error sign! origin_string[1741071279971yjHTlVOB6X6Man1Ah55000category=linear&symbol=BTCUSDT&startTime=1739948066013&endTime=1740552866013&limit=100&timestamp=1741071279971]', 'result': {}, 'retExtInfo': {}, 'time': 1741071280095}
2025-03-04 15:54:41,097 - services.trade_history_service - INFO - 기간별 조회: 2025-02-26 ~ 2025-03-04
2025-03-04 15:54:41,097 - services.trade_history_service - DEBUG - API 요청 파라미터: {'category': 'linear', 'symbol': 'BTCUSDT', 'startTime': '1740552866013', 'endTime': '1741071266013', 'limit': 100}
2025-03-04 15:54:41,345 - services.trade_history_service - DEBUG - API 응답: {'retCode': 10004, 'retMsg': 'error sign! origin_string[1741071281088yjHTlVOB6X6Man1Ah55000category=linear&symbol=BTCUSDT&startTime=1740552866013&endTime=1741071266013&limit=100&timestamp=1741071281088]', 'result': {}, 'retExtInfo': {}, 'time': 1741071281335}
2025-03-04 15:54:42,359 - telegram_bot.bot - INFO - Application 빌드 시작...
2025-03-04 15:54:42,743 - apscheduler.scheduler - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2025-03-04 15:54:42,743 - telegram_bot.bot - INFO - 핸들러 초기화 완료
2025-03-04 15:54:42,743 - telegram_bot.bot - INFO - 봇 초기화 완료, 시작 준비 중...
2025-03-04 15:54:42,743 - telegram_bot.bot - INFO - 봇 시작 시도...
2025-03-04 15:54:42,743 - telegram_bot.bot - INFO - === 봇 시작 시도 ===
2025-03-04 15:54:43,843 - apscheduler.scheduler - INFO - Scheduler started
2025-03-04 15:54:43,843 - telegram.ext.Application - INFO - Application started
2025-03-04 15:54:44,117 - telegram_bot.bot - INFO - 🤖 바이빗 트레이딩 봇이 시작되었습니다
2025-03-04 15:58:32,881 - main - INFO - 환경변수 및 설정 초기화 중...
2025-03-04 15:58:32,881 - main - INFO - Bybit 테스트넷 클라이언트 초기화 중...
2025-03-04 15:58:33,079 - main - INFO - 서비스 초기화 중...
2025-03-04 15:58:33,079 - main - INFO - 마켓 데이터 서비스 중...
2025-03-04 15:58:34,559 - services.market_data_service - INFO - 마켓 데이터 로드 완료
2025-03-04 15:58:34,788 - telegram_bot.bot - INFO - 텔레그램 설정 로드:
2025-03-04 15:58:34,788 - telegram_bot.bot - INFO - - admin_chat_id: 583881676
2025-03-04 15:58:34,788 - telegram_bot.bot - INFO - - alert_chat_ids: [-1002464784986]
2025-03-04 15:58:35,161 - apscheduler.scheduler - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2025-03-04 15:58:35,161 - telegram_bot.bot - INFO - 봇 초기화 시작...
2025-03-04 15:58:35,177 - services.trade_history_service - INFO - === 포지션 정보 초기화 시작 ===
2025-03-04 15:58:35,177 - services.trade_history_service - INFO - 조회 기간: 2024-12-04 ~ 2025-03-04
2025-03-04 15:58:35,178 - services.trade_store - INFO - 날짜 범위 조회: 20241204 ~ 20250304
2025-03-04 15:58:35,178 - services.trade_store - INFO - 날짜: 20241204, 포지션 수: 0건
2025-03-04 15:58:35,179 - services.trade_store - INFO - 날짜: 20241205, 포지션 수: 0건
2025-03-04 15:58:35,179 - services.trade_store - INFO - 날짜: 20241206, 포지션 수: 0건
2025-03-04 15:58:35,179 - services.trade_store - INFO - 날짜: 20241207, 포지션 수: 0건
2025-03-04 15:58:35,179 - services.trade_store - INFO - 날짜: 20241208, 포지션 수: 0건
2025-03-04 15:58:35,179 - services.trade_store - INFO - 날짜: 20241209, 포지션 수: 0건
2025-03-04 15:58:35,179 - services.trade_store - INFO - 날짜: 20241210, 포지션 수: 0건
2025-03-04 15:58:35,179 - services.trade_store - INFO - 날짜: 20241211, 포지션 수: 0건
2025-03-04 15:58:35,179 - services.trade_store - INFO - 날짜: 20241212, 포지션 수: 0건
2025-03-04 15:58:35,179 - services.trade_store - INFO - 날짜: 20241213, 포지션 수: 0건
2025-03-04 15:58:35,179 - services.trade_store - INFO - 날짜: 20241214, 포지션 수: 0건
2025-03-04 15:58:35,179 - services.trade_store - INFO - 날짜: 20241215, 포지션 수: 0건
2025-03-04 15:58:35,179 - services.trade_store - INFO - 날짜: 20241216, 포지션 수: 0건
2025-03-04 15:58:35,179 - services.trade_store - INFO - 날짜: 20241217, 포지션 수: 0건
2025-03-04 15:58:35,179 - services.trade_store - INFO - 날짜: 20241218, 포지션 수: 0건
2025-03-04 15:58:35,179 - services.trade_store - INFO - 날짜: 20241219, 포지션 수: 0건
2025-03-04 15:58:35,179 - services.trade_store - INFO - 날짜: 20241220, 포지션 수: 0건
2025-03-04 15:58:35,179 - services.trade_store - INFO - 날짜: 20241221, 포지션 수: 0건
2025-03-04 15:58:35,179 - services.trade_store - INFO - 날짜: 20241222, 포지션 수: 0건
2025-03-04 15:58:35,179 - services.trade_store - INFO - 날짜: 20241223, 포지션 수: 0건
2025-03-04 15:58:35,179 - services.trade_store - INFO - 날짜: 20241224, 포지션 수: 0건
2025-03-04 15:58:35,179 - services.trade_store - INFO - 날짜: 20241225, 포지션 수: 0건
2025-03-04 15:58:35,179 - services.trade_store - INFO - 날짜: 20241226, 포지션 수: 0건
2025-03-04 15:58:35,181 - services.trade_store - INFO - 날짜: 20241227, 포지션 수: 0건
2025-03-04 15:58:35,181 - services.trade_store - INFO - 날짜: 20241228, 포지션 수: 0건
2025-03-04 15:58:35,181 - services.trade_store - INFO - 날짜: 20241229, 포지션 수: 0건
2025-03-04 15:58:35,181 - services.trade_store - INFO - 날짜: 20241230, 포지션 수: 0건
2025-03-04 15:58:35,181 - services.trade_store - INFO - 날짜: 20241231, 포지션 수: 0건
2025-03-04 15:58:35,182 - services.trade_store - INFO - 날짜: 20250101, 포지션 수: 0건
2025-03-04 15:58:35,182 - services.trade_store - INFO - 날짜: 20250102, 포지션 수: 0건
2025-03-04 15:58:35,182 - services.trade_store - INFO - 날짜: 20250103, 포지션 수: 0건
2025-03-04 15:58:35,182 - services.trade_store - INFO - 날짜: 20250104, 포지션 수: 0건
2025-03-04 15:58:35,182 - services.trade_store - INFO - 날짜: 20250105, 포지션 수: 0건
2025-03-04 15:58:35,182 - services.trade_store - INFO - 날짜: 20250106, 포지션 수: 0건
2025-03-04 15:58:35,182 - services.trade_store - INFO - 날짜: 20250107, 포지션 수: 0건
2025-03-04 15:58:35,183 - services.trade_store - INFO - 날짜: 20250108, 포지션 수: 0건
2025-03-04 15:58:35,183 - services.trade_store - INFO - 날짜: 20250109, 포지션 수: 0건
2025-03-04 15:58:35,183 - services.trade_store - INFO - 날짜: 20250110, 포지션 수: 0건
2025-03-04 15:58:35,183 - services.trade_store - INFO - 날짜: 20250111, 포지션 수: 0건
2025-03-04 15:58:35,183 - services.trade_store - INFO - 날짜: 20250112, 포지션 수: 0건
2025-03-04 15:58:35,183 - services.trade_store - INFO - 날짜: 20250113, 포지션 수: 0건
2025-03-04 15:58:35,184 - services.trade_store - INFO - 날짜: 20250114, 포지션 수: 0건
2025-03-04 15:58:35,184 - services.trade_store - INFO - 날짜: 20250115, 포지션 수: 0건
2025-03-04 15:58:35,184 - services.trade_store - INFO - 날짜: 20250116, 포지션 수: 0건
2025-03-04 15:58:35,184 - services.trade_store - INFO - 날짜: 20250117, 포지션 수: 0건
2025-03-04 15:58:35,184 - services.trade_store - INFO - 날짜: 20250118, 포지션 수: 0건
2025-03-04 15:58:35,184 - services.trade_store - INFO - 날짜: 20250119, 포지션 수: 0건
2025-03-04 15:58:35,184 - services.trade_store - INFO - 날짜: 20250120, 포지션 수: 0건
2025-03-04 15:58:35,184 - services.trade_store - INFO - 날짜: 20250121, 포지션 수: 0건
2025-03-04 15:58:35,185 - services.trade_store - INFO - 날짜: 20250122, 포지션 수: 0건
2025-03-04 15:58:35,185 - services.trade_store - INFO - 날짜: 20250123, 포지션 수: 0건
2025-03-04 15:58:35,185 - services.trade_store - INFO - 날짜: 20250124, 포지션 수: 0건
2025-03-04 15:58:35,185 - services.trade_store - INFO - 날짜: 20250125, 포지션 수: 0건
2025-03-04 15:58:35,185 - services.trade_store - INFO - 날짜: 20250126, 포지션 수: 0건
2025-03-04 15:58:35,185 - services.trade_store - INFO - 날짜: 20250127, 포지션 수: 0건
2025-03-04 15:58:35,185 - services.trade_store - INFO - 날짜: 20250128, 포지션 수: 0건
2025-03-04 15:58:35,185 - services.trade_store - INFO - 날짜: 20250129, 포지션 수: 0건
2025-03-04 15:58:35,186 - services.trade_store - INFO - 날짜: 20250130, 포지션 수: 0건
2025-03-04 15:58:35,186 - services.trade_store - INFO - 날짜: 20250131, 포지션 수: 0건
2025-03-04 15:58:35,186 - services.trade_store - INFO - 날짜: 20250201, 포지션 수: 0건
2025-03-04 15:58:35,186 - services.trade_store - INFO - 날짜: 20250202, 포지션 수: 0건
2025-03-04 15:58:35,186 - services.trade_store - INFO - 날짜: 20250203, 포지션 수: 0건
2025-03-04 15:58:35,186 - services.trade_store - INFO - 날짜: 20250204, 포지션 수: 0건
2025-03-04 15:58:35,186 - services.trade_store - INFO - 날짜: 20250205, 포지션 수: 0건
2025-03-04 15:58:35,187 - services.trade_store - INFO - 날짜: 20250206, 포지션 수: 0건
2025-03-04 15:58:35,187 - services.trade_store - INFO - 날짜: 20250207, 포지션 수: 0건
2025-03-04 15:58:35,187 - services.trade_store - INFO - 날짜: 20250208, 포지션 수: 0건
2025-03-04 15:58:35,187 - services.trade_store - INFO - 날짜: 20250209, 포지션 수: 0건
2025-03-04 15:58:35,187 - services.trade_store - INFO - 날짜: 20250210, 포지션 수: 0건
2025-03-04 15:58:35,187 - services.trade_store - INFO - 날짜: 20250211, 포지션 수: 0건
2025-03-04 15:58:35,187 - services.trade_store - INFO - 날짜: 20250212, 포지션 수: 0건
2025-03-04 15:58:35,188 - services.trade_store - INFO - 날짜: 20250213, 포지션 수: 0건
2025-03-04 15:58:35,188 - services.trade_store - INFO - 날짜: 20250214, 포지션 수: 0건
2025-03-04 15:58:35,188 - services.trade_store - INFO - 날짜: 20250215, 포지션 수: 0건
2025-03-04 15:58:35,188 - services.trade_store - INFO - 날짜: 20250216, 포지션 수: 0건
2025-03-04 15:58:35,188 - services.trade_store - INFO - 날짜: 20250217, 포지션 수: 0건
2025-03-04 15:58:35,188 - services.trade_store - INFO - 날짜: 20250218, 포지션 수: 0건
2025-03-04 15:58:35,189 - services.trade_store - INFO - 날짜: 20250219, 포지션 수: 0건
2025-03-04 15:58:35,189 - services.trade_store - INFO - 날짜: 20250220, 포지션 수: 0건
2025-03-04 15:58:35,189 - services.trade_store - INFO - 날짜: 20250221, 포지션 수: 0건
2025-03-04 15:58:35,189 - services.trade_store - INFO - 날짜: 20250222, 포지션 수: 0건
2025-03-04 15:58:35,189 - services.trade_store - INFO - 날짜: 20250223, 포지션 수: 0건
2025-03-04 15:58:35,189 - services.trade_store - INFO - 날짜: 20250224, 포지션 수: 0건
2025-03-04 15:58:35,189 - services.trade_store - INFO - 날짜: 20250225, 포지션 수: 0건
2025-03-04 15:58:35,189 - services.trade_store - INFO - 날짜: 20250226, 포지션 수: 0건
2025-03-04 15:58:35,190 - services.trade_store - INFO - 날짜: 20250227, 포지션 수: 0건
2025-03-04 15:58:35,190 - services.trade_store - INFO - 날짜: 20250228, 포지션 수: 0건
2025-03-04 15:58:35,190 - services.trade_store - INFO - 날짜: 20250301, 포지션 수: 0건
2025-03-04 15:58:35,190 - services.trade_store - INFO - 날짜: 20250302, 포지션 수: 0건
2025-03-04 15:58:35,190 - services.trade_store - INFO - 날짜: 20250303, 포지션 수: 0건
2025-03-04 15:58:35,190 - services.trade_store - INFO - 날짜: 20250304, 포지션 수: 0건
2025-03-04 15:58:35,190 - services.trade_store - INFO - 총 0건의 포지션 데이터 로드됨
2025-03-04 15:58:35,190 - services.trade_history_service - INFO - 기존 데이터: 0건
2025-03-04 15:58:35,190 - services.trade_history_service - INFO - 기존 데이터가 없습니다. 전체 기간 조회를 시작합니다.
2025-03-04 15:58:35,191 - services.trade_history_service - INFO - 기간별 조회: 2024-12-04 ~ 2024-12-11
2025-03-04 15:58:35,191 - services.trade_history_service - DEBUG - API 요청 파라미터: {'category': 'linear', 'symbol': 'BTCUSDT', 'startTime': '1733295515177', 'endTime': '1733900315177', 'limit': 100}
2025-03-04 15:58:35,333 - exchange.bybit_client - INFO - 서버 시간 동기화 완료: offset = -9ms
2025-03-04 15:58:35,627 - services.trade_history_service - DEBUG - API 응답: {'retCode': 10004, 'retMsg': 'error sign! origin_string[1741071515324yjHTlVOB6X6Man1Ah55000category=linear&symbol=BTCUSDT&startTime=1733295515177&endTime=1733900315177&limit=100&timestamp=1741071515324]', 'result': {}, 'retExtInfo': {}, 'time': 1741071515622}
2025-03-04 15:58:36,632 - services.trade_history_service - INFO - 기간별 조회: 2024-12-11 ~ 2024-12-18
2025-03-04 15:58:36,632 - services.trade_history_service - DEBUG - API 요청 파라미터: {'category': 'linear', 'symbol': 'BTCUSDT', 'startTime': '1733900315177', 'endTime': '1734505115177', 'limit': 100}
2025-03-04 15:58:36,757 - services.trade_history_service - DEBUG - API 응답: {'retCode': 10004, 'retMsg': 'error sign! origin_string[1741071516623yjHTlVOB6X6Man1Ah55000category=linear&symbol=BTCUSDT&startTime=1733900315177&endTime=1734505115177&limit=100&timestamp=1741071516623]', 'result': {}, 'retExtInfo': {}, 'time': 1741071516747}
2025-03-04 15:58:37,772 - services.trade_history_service - INFO - 기간별 조회: 2024-12-18 ~ 2024-12-25
2025-03-04 15:58:37,772 - services.trade_history_service - DEBUG - API 요청 파라미터: {'category': 'linear', 'symbol': 'BTCUSDT', 'startTime': '1734505115177', 'endTime': '1735109915177', 'limit': 100}
2025-03-04 15:58:37,892 - services.trade_history_service - DEBUG - API 응답: {'retCode': 10004, 'retMsg': 'error sign! origin_string[1741071517763yjHTlVOB6X6Man1Ah55000category=linear&symbol=BTCUSDT&startTime=1734505115177&endTime=1735109915177&limit=100&timestamp=1741071517763]', 'result': {}, 'retExtInfo': {}, 'time': 1741071517883}
2025-03-04 15:58:38,905 - services.trade_history_service - INFO - 기간별 조회: 2024-12-25 ~ 2025-01-01
2025-03-04 15:58:38,905 - services.trade_history_service - DEBUG - API 요청 파라미터: {'category': 'linear', 'symbol': 'BTCUSDT', 'startTime': '1735109915177', 'endTime': '1735714715177', 'limit': 100}
2025-03-04 15:58:39,140 - services.trade_history_service - DEBUG - API 응답: {'retCode': 10004, 'retMsg': 'error sign! origin_string[1741071518896yjHTlVOB6X6Man1Ah55000category=linear&symbol=BTCUSDT&startTime=1735109915177&endTime=1735714715177&limit=100&timestamp=1741071518896]', 'result': {}, 'retExtInfo': {}, 'time': 1741071519147}
2025-03-04 15:58:40,138 - services.trade_history_service - INFO - 기간별 조회: 2025-01-01 ~ 2025-01-08
2025-03-04 15:58:40,138 - services.trade_history_service - DEBUG - API 요청 파라미터: {'category': 'linear', 'symbol': 'BTCUSDT', 'startTime': '1735714715177', 'endTime': '1736319515177', 'limit': 100}
2025-03-04 15:58:40,254 - services.trade_history_service - DEBUG - API 응답: {'retCode': 10004, 'retMsg': 'error sign! origin_string[1741071520129yjHTlVOB6X6Man1Ah55000category=linear&symbol=BTCUSDT&startTime=1735714715177&endTime=1736319515177&limit=100&timestamp=1741071520129]', 'result': {}, 'retExtInfo': {}, 'time': 1741071520246}
2025-03-04 15:58:41,261 - services.trade_history_service - INFO - 기간별 조회: 2025-01-08 ~ 2025-01-15
2025-03-04 15:58:41,261 - services.trade_history_service - DEBUG - API 요청 파라미터: {'category': 'linear', 'symbol': 'BTCUSDT', 'startTime': '1736319515177', 'endTime': '1736924315177', 'limit': 100}
2025-03-04 15:58:41,383 - services.trade_history_service - DEBUG - API 응답: {'retCode': 10004, 'retMsg': 'error sign! origin_string[1741071521252yjHTlVOB6X6Man1Ah55000category=linear&symbol=BTCUSDT&startTime=1736319515177&endTime=1736924315177&limit=100&timestamp=1741071521252]', 'result': {}, 'retExtInfo': {}, 'time': 1741071521379}
2025-03-04 15:58:42,387 - services.trade_history_service - INFO - 기간별 조회: 2025-01-15 ~ 2025-01-22
2025-03-04 15:58:42,387 - services.trade_history_service - DEBUG - API 요청 파라미터: {'category': 'linear', 'symbol': 'BTCUSDT', 'startTime': '1736924315177', 'endTime': '1737529115177', 'limit': 100}
2025-03-04 15:58:42,501 - services.trade_history_service - DEBUG - API 응답: {'retCode': 10004, 'retMsg': 'error sign! origin_string[1741071522378yjHTlVOB6X6Man1Ah55000category=linear&symbol=BTCUSDT&startTime=1736924315177&endTime=1737529115177&limit=100&timestamp=1741071522378]', 'result': {}, 'retExtInfo': {}, 'time': 1741071522494}
2025-03-04 15:58:43,515 - services.trade_history_service - INFO - 기간별 조회: 2025-01-22 ~ 2025-01-29
2025-03-04 15:58:43,515 - services.trade_history_service - DEBUG - API 요청 파라미터: {'category': 'linear', 'symbol': 'BTCUSDT', 'startTime': '1737529115177', 'endTime': '1738133915177', 'limit': 100}
2025-03-04 15:58:43,633 - services.trade_history_service - DEBUG - API 응답: {'retCode': 10004, 'retMsg': 'error sign! origin_string[1741071523506yjHTlVOB6X6Man1Ah55000category=linear&symbol=BTCUSDT&startTime=1737529115177&endTime=1738133915177&limit=100&timestamp=1741071523506]', 'result': {}, 'retExtInfo': {}, 'time': 1741071523626}
2025-03-04 15:58:44,648 - services.trade_history_service - INFO - 기간별 조회: 2025-01-29 ~ 2025-02-05
2025-03-04 15:58:44,648 - services.trade_history_service - DEBUG - API 요청 파라미터: {'category': 'linear', 'symbol': 'BTCUSDT', 'startTime': '1738133915177', 'endTime': '1738738715177', 'limit': 100}
2025-03-04 15:58:44,903 - services.trade_history_service - DEBUG - API 응답: {'retCode': 10004, 'retMsg': 'error sign! origin_string[1741071524639yjHTlVOB6X6Man1Ah55000category=linear&symbol=BTCUSDT&startTime=1738133915177&endTime=1738738715177&limit=100&timestamp=1741071524639]', 'result': {}, 'retExtInfo': {}, 'time': 1741071524898}
2025-03-04 15:58:45,894 - services.trade_history_service - INFO - 기간별 조회: 2025-02-05 ~ 2025-02-12
2025-03-04 15:58:45,895 - services.trade_history_service - DEBUG - API 요청 파라미터: {'category': 'linear', 'symbol': 'BTCUSDT', 'startTime': '1738738715177', 'endTime': '1739343515177', 'limit': 100}
2025-03-04 15:58:46,013 - services.trade_history_service - DEBUG - API 응답: {'retCode': 10004, 'retMsg': 'error sign! origin_string[1741071525886yjHTlVOB6X6Man1Ah55000category=linear&symbol=BTCUSDT&startTime=1738738715177&endTime=1739343515177&limit=100&timestamp=1741071525886]', 'result': {}, 'retExtInfo': {}, 'time': 1741071526006}
2025-03-04 15:58:47,008 - services.trade_history_service - INFO - 기간별 조회: 2025-02-12 ~ 2025-02-19
2025-03-04 15:58:47,008 - services.trade_history_service - DEBUG - API 요청 파라미터: {'category': 'linear', 'symbol': 'BTCUSDT', 'startTime': '1739343515177', 'endTime': '1739948315177', 'limit': 100}
2025-03-04 15:58:47,120 - services.trade_history_service - DEBUG - API 응답: {'retCode': 10004, 'retMsg': 'error sign! origin_string[1741071526999yjHTlVOB6X6Man1Ah55000category=linear&symbol=BTCUSDT&startTime=1739343515177&endTime=1739948315177&limit=100&timestamp=1741071526999]', 'result': {}, 'retExtInfo': {}, 'time': 1741071527111}
2025-03-04 15:58:48,126 - services.trade_history_service - INFO - 기간별 조회: 2025-02-19 ~ 2025-02-26
2025-03-04 15:58:48,126 - services.trade_history_service - DEBUG - API 요청 파라미터: {'category': 'linear', 'symbol': 'BTCUSDT', 'startTime': '1739948315177', 'endTime': '1740553115177', 'limit': 100}
2025-03-04 15:58:48,245 - services.trade_history_service - DEBUG - API 응답: {'retCode': 10004, 'retMsg': 'error sign! origin_string[1741071528117yjHTlVOB6X6Man1Ah55000category=linear&symbol=BTCUSDT&startTime=1739948315177&endTime=1740553115177&limit=100&timestamp=1741071528117]', 'result': {}, 'retExtInfo': {}, 'time': 1741071528236}
2025-03-04 15:58:49,250 - services.trade_history_service - INFO - 기간별 조회: 2025-02-26 ~ 2025-03-04
2025-03-04 15:58:49,251 - services.trade_history_service - DEBUG - API 요청 파라미터: {'category': 'linear', 'symbol': 'BTCUSDT', 'startTime': '1740553115177', 'endTime': '1741071515177', 'limit': 100}
2025-03-04 15:58:49,367 - services.trade_history_service - DEBUG - API 응답: {'retCode': 10004, 'retMsg': 'error sign! origin_string[1741071529242yjHTlVOB6X6Man1Ah55000category=linear&symbol=BTCUSDT&startTime=1740553115177&endTime=1741071515177&limit=100&timestamp=1741071529242]', 'result': {}, 'retExtInfo': {}, 'time': 1741071529360}
2025-03-04 15:58:50,384 - telegram_bot.bot - INFO - Application 빌드 시작...
2025-03-04 15:58:50,763 - apscheduler.scheduler - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2025-03-04 15:58:50,764 - telegram_bot.bot - INFO - 핸들러 초기화 완료
2025-03-04 15:58:50,765 - telegram_bot.bot - INFO - 봇 초기화 완료, 시작 준비 중...
2025-03-04 15:58:50,765 - telegram_bot.bot - INFO - 봇 시작 시도...
2025-03-04 15:58:50,766 - telegram_bot.bot - INFO - === 봇 시작 시도 ===
2025-03-04 15:58:51,814 - apscheduler.scheduler - INFO - Scheduler started
2025-03-04 15:58:51,814 - telegram.ext.Application - INFO - Application started
2025-03-04 15:58:52,077 - telegram_bot.bot - INFO - 🤖 바이빗 트레이딩 봇이 시작되었습니다
2025-03-04 16:00:52,873 - main - INFO - 환경변수 및 설정 초기화 중...
2025-03-04 16:00:52,873 - main - INFO - Bybit 테스트넷 클라이언트 초기화 중...
2025-03-04 16:00:53,071 - main - INFO - 서비스 초기화 중...
2025-03-04 16:00:53,071 - main - INFO - 마켓 데이터 서비스 중...
2025-03-04 16:00:54,566 - services.market_data_service - INFO - 마켓 데이터 로드 완료
2025-03-04 16:00:54,778 - telegram_bot.bot - INFO - 텔레그램 설정 로드:
2025-03-04 16:00:54,778 - telegram_bot.bot - INFO - - admin_chat_id: 583881676
2025-03-04 16:00:54,778 - telegram_bot.bot - INFO - - alert_chat_ids: [-1002464784986]
2025-03-04 16:00:55,178 - apscheduler.scheduler - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2025-03-04 16:00:55,179 - telegram_bot.bot - INFO - 봇 초기화 시작...
2025-03-04 16:00:55,180 - services.trade_history_service - INFO - === 포지션 정보 초기화 시작 ===
2025-03-04 16:00:55,180 - services.trade_history_service - INFO - 조회 기간: 2024-12-04 ~ 2025-03-04
2025-03-04 16:00:55,180 - services.trade_store - INFO - 날짜 범위 조회: 20241204 ~ 20250304
2025-03-04 16:00:55,180 - services.trade_store - INFO - 날짜: 20241204, 포지션 수: 0건
2025-03-04 16:00:55,180 - services.trade_store - INFO - 날짜: 20241205, 포지션 수: 0건
2025-03-04 16:00:55,180 - services.trade_store - INFO - 날짜: 20241206, 포지션 수: 0건
2025-03-04 16:00:55,180 - services.trade_store - INFO - 날짜: 20241207, 포지션 수: 0건
2025-03-04 16:00:55,180 - services.trade_store - INFO - 날짜: 20241208, 포지션 수: 0건
2025-03-04 16:00:55,180 - services.trade_store - INFO - 날짜: 20241209, 포지션 수: 0건
2025-03-04 16:00:55,180 - services.trade_store - INFO - 날짜: 20241210, 포지션 수: 0건
2025-03-04 16:00:55,180 - services.trade_store - INFO - 날짜: 20241211, 포지션 수: 0건
2025-03-04 16:00:55,180 - services.trade_store - INFO - 날짜: 20241212, 포지션 수: 0건
2025-03-04 16:00:55,180 - services.trade_store - INFO - 날짜: 20241213, 포지션 수: 0건
2025-03-04 16:00:55,180 - services.trade_store - INFO - 날짜: 20241214, 포지션 수: 0건
2025-03-04 16:00:55,180 - services.trade_store - INFO - 날짜: 20241215, 포지션 수: 0건
2025-03-04 16:00:55,180 - services.trade_store - INFO - 날짜: 20241216, 포지션 수: 0건
2025-03-04 16:00:55,180 - services.trade_store - INFO - 날짜: 20241217, 포지션 수: 0건
2025-03-04 16:00:55,180 - services.trade_store - INFO - 날짜: 20241218, 포지션 수: 0건
2025-03-04 16:00:55,180 - services.trade_store - INFO - 날짜: 20241219, 포지션 수: 0건
2025-03-04 16:00:55,180 - services.trade_store - INFO - 날짜: 20241220, 포지션 수: 0건
2025-03-04 16:00:55,180 - services.trade_store - INFO - 날짜: 20241221, 포지션 수: 0건
2025-03-04 16:00:55,180 - services.trade_store - INFO - 날짜: 20241222, 포지션 수: 0건
2025-03-04 16:00:55,180 - services.trade_store - INFO - 날짜: 20241223, 포지션 수: 0건
2025-03-04 16:00:55,180 - services.trade_store - INFO - 날짜: 20241224, 포지션 수: 0건
2025-03-04 16:00:55,180 - services.trade_store - INFO - 날짜: 20241225, 포지션 수: 0건
2025-03-04 16:00:55,180 - services.trade_store - INFO - 날짜: 20241226, 포지션 수: 0건
2025-03-04 16:00:55,180 - services.trade_store - INFO - 날짜: 20241227, 포지션 수: 0건
2025-03-04 16:00:55,180 - services.trade_store - INFO - 날짜: 20241228, 포지션 수: 0건
2025-03-04 16:00:55,180 - services.trade_store - INFO - 날짜: 20241229, 포지션 수: 0건
2025-03-04 16:00:55,180 - services.trade_store - INFO - 날짜: 20241230, 포지션 수: 0건
2025-03-04 16:00:55,180 - services.trade_store - INFO - 날짜: 20241231, 포지션 수: 0건
2025-03-04 16:00:55,185 - services.trade_store - INFO - 날짜: 20250101, 포지션 수: 0건
2025-03-04 16:00:55,185 - services.trade_store - INFO - 날짜: 20250102, 포지션 수: 0건
2025-03-04 16:00:55,185 - services.trade_store - INFO - 날짜: 20250103, 포지션 수: 0건
2025-03-04 16:00:55,185 - services.trade_store - INFO - 날짜: 20250104, 포지션 수: 0건
2025-03-04 16:00:55,186 - services.trade_store - INFO - 날짜: 20250105, 포지션 수: 0건
2025-03-04 16:00:55,186 - services.trade_store - INFO - 날짜: 20250106, 포지션 수: 0건
2025-03-04 16:00:55,186 - services.trade_store - INFO - 날짜: 20250107, 포지션 수: 0건
2025-03-04 16:00:55,186 - services.trade_store - INFO - 날짜: 20250108, 포지션 수: 0건
2025-03-04 16:00:55,186 - services.trade_store - INFO - 날짜: 20250109, 포지션 수: 0건
2025-03-04 16:00:55,186 - services.trade_store - INFO - 날짜: 20250110, 포지션 수: 0건
2025-03-04 16:00:55,186 - services.trade_store - INFO - 날짜: 20250111, 포지션 수: 0건
2025-03-04 16:00:55,186 - services.trade_store - INFO - 날짜: 20250112, 포지션 수: 0건
2025-03-04 16:00:55,187 - services.trade_store - INFO - 날짜: 20250113, 포지션 수: 0건
2025-03-04 16:00:55,187 - services.trade_store - INFO - 날짜: 20250114, 포지션 수: 0건
2025-03-04 16:00:55,187 - services.trade_store - INFO - 날짜: 20250115, 포지션 수: 0건
2025-03-04 16:00:55,187 - services.trade_store - INFO - 날짜: 20250116, 포지션 수: 0건
2025-03-04 16:00:55,187 - services.trade_store - INFO - 날짜: 20250117, 포지션 수: 0건
2025-03-04 16:00:55,187 - services.trade_store - INFO - 날짜: 20250118, 포지션 수: 0건
2025-03-04 16:00:55,187 - services.trade_store - INFO - 날짜: 20250119, 포지션 수: 0건
2025-03-04 16:00:55,187 - services.trade_store - INFO - 날짜: 20250120, 포지션 수: 0건
2025-03-04 16:00:55,187 - services.trade_store - INFO - 날짜: 20250121, 포지션 수: 0건
2025-03-04 16:00:55,188 - services.trade_store - INFO - 날짜: 20250122, 포지션 수: 0건
2025-03-04 16:00:55,188 - services.trade_store - INFO - 날짜: 20250123, 포지션 수: 0건
2025-03-04 16:00:55,188 - services.trade_store - INFO - 날짜: 20250124, 포지션 수: 0건
2025-03-04 16:00:55,188 - services.trade_store - INFO - 날짜: 20250125, 포지션 수: 0건
2025-03-04 16:00:55,188 - services.trade_store - INFO - 날짜: 20250126, 포지션 수: 0건
2025-03-04 16:00:55,188 - services.trade_store - INFO - 날짜: 20250127, 포지션 수: 0건
2025-03-04 16:00:55,188 - services.trade_store - INFO - 날짜: 20250128, 포지션 수: 0건
2025-03-04 16:00:55,188 - services.trade_store - INFO - 날짜: 20250129, 포지션 수: 0건
2025-03-04 16:00:55,189 - services.trade_store - INFO - 날짜: 20250130, 포지션 수: 0건
2025-03-04 16:00:55,189 - services.trade_store - INFO - 날짜: 20250131, 포지션 수: 0건
2025-03-04 16:00:55,189 - services.trade_store - INFO - 날짜: 20250201, 포지션 수: 0건
2025-03-04 16:00:55,189 - services.trade_store - INFO - 날짜: 20250202, 포지션 수: 0건
2025-03-04 16:00:55,189 - services.trade_store - INFO - 날짜: 20250203, 포지션 수: 0건
2025-03-04 16:00:55,189 - services.trade_store - INFO - 날짜: 20250204, 포지션 수: 0건
2025-03-04 16:00:55,189 - services.trade_store - INFO - 날짜: 20250205, 포지션 수: 0건
2025-03-04 16:00:55,190 - services.trade_store - INFO - 날짜: 20250206, 포지션 수: 0건
2025-03-04 16:00:55,190 - services.trade_store - INFO - 날짜: 20250207, 포지션 수: 0건
2025-03-04 16:00:55,190 - services.trade_store - INFO - 날짜: 20250208, 포지션 수: 0건
2025-03-04 16:00:55,190 - services.trade_store - INFO - 날짜: 20250209, 포지션 수: 0건
2025-03-04 16:00:55,190 - services.trade_store - INFO - 날짜: 20250210, 포지션 수: 0건
2025-03-04 16:00:55,190 - services.trade_store - INFO - 날짜: 20250211, 포지션 수: 0건
2025-03-04 16:00:55,190 - services.trade_store - INFO - 날짜: 20250212, 포지션 수: 0건
2025-03-04 16:00:55,190 - services.trade_store - INFO - 날짜: 20250213, 포지션 수: 0건
2025-03-04 16:00:55,190 - services.trade_store - INFO - 날짜: 20250214, 포지션 수: 0건
2025-03-04 16:00:55,191 - services.trade_store - INFO - 날짜: 20250215, 포지션 수: 0건
2025-03-04 16:00:55,191 - services.trade_store - INFO - 날짜: 20250216, 포지션 수: 0건
2025-03-04 16:00:55,191 - services.trade_store - INFO - 날짜: 20250217, 포지션 수: 0건
2025-03-04 16:00:55,191 - services.trade_store - INFO - 날짜: 20250218, 포지션 수: 0건
2025-03-04 16:00:55,192 - services.trade_store - INFO - 날짜: 20250219, 포지션 수: 0건
2025-03-04 16:00:55,192 - services.trade_store - INFO - 날짜: 20250220, 포지션 수: 0건
2025-03-04 16:00:55,192 - services.trade_store - INFO - 날짜: 20250221, 포지션 수: 0건
2025-03-04 16:00:55,192 - services.trade_store - INFO - 날짜: 20250222, 포지션 수: 0건
2025-03-04 16:00:55,193 - services.trade_store - INFO - 날짜: 20250223, 포지션 수: 0건
2025-03-04 16:00:55,193 - services.trade_store - INFO - 날짜: 20250224, 포지션 수: 0건
2025-03-04 16:00:55,193 - services.trade_store - INFO - 날짜: 20250225, 포지션 수: 0건
2025-03-04 16:00:55,193 - services.trade_store - INFO - 날짜: 20250226, 포지션 수: 0건
2025-03-04 16:00:55,193 - services.trade_store - INFO - 날짜: 20250227, 포지션 수: 0건
2025-03-04 16:00:55,193 - services.trade_store - INFO - 날짜: 20250228, 포지션 수: 0건
2025-03-04 16:00:55,194 - services.trade_store - INFO - 날짜: 20250301, 포지션 수: 0건
2025-03-04 16:00:55,194 - services.trade_store - INFO - 날짜: 20250302, 포지션 수: 0건
2025-03-04 16:00:55,194 - services.trade_store - INFO - 날짜: 20250303, 포지션 수: 0건
2025-03-04 16:00:55,194 - services.trade_store - INFO - 날짜: 20250304, 포지션 수: 0건
2025-03-04 16:00:55,194 - services.trade_store - INFO - 총 0건의 포지션 데이터 로드됨
2025-03-04 16:00:55,194 - services.trade_history_service - INFO - 기존 데이터: 0건
2025-03-04 16:00:55,194 - services.trade_history_service - INFO - 기존 데이터가 없습니다. 전체 기간 조회를 시작합니다.
2025-03-04 16:00:55,195 - services.trade_history_service - INFO - 기간별 조회: 2024-12-04 ~ 2024-12-11
2025-03-04 16:00:55,195 - services.trade_history_service - DEBUG - API 요청 파라미터: {'category': 'linear', 'symbol': 'BTCUSDT', 'startTime': '1733295655180', 'endTime': '1733900455180', 'limit': 100}
2025-03-04 16:00:55,335 - exchange.bybit_client - INFO - 서버 시간 동기화 완료: offset = -8ms
2025-03-04 16:00:55,452 - services.trade_history_service - DEBUG - API 응답: {'retCode': 10004, 'retMsg': 'error sign! origin_string[1741071655328yjHTlVOB6X6Man1Ah55000category=linear&symbol=BTCUSDT&startTime=1733295655180&endTime=1733900455180&limit=100&timestamp=1741071655328]', 'result': {}, 'retExtInfo': {}, 'time': 1741071655450}
2025-03-04 16:00:56,452 - services.trade_history_service - INFO - 기간별 조회: 2024-12-11 ~ 2024-12-18
2025-03-04 16:00:56,453 - services.trade_history_service - DEBUG - API 요청 파라미터: {'category': 'linear', 'symbol': 'BTCUSDT', 'startTime': '1733900455180', 'endTime': '1734505255180', 'limit': 100}
2025-03-04 16:00:56,588 - services.trade_history_service - DEBUG - API 응답: {'retCode': 10004, 'retMsg': 'error sign! origin_string[1741071656445yjHTlVOB6X6Man1Ah55000category=linear&symbol=BTCUSDT&startTime=1733900455180&endTime=1734505255180&limit=100&timestamp=1741071656445]', 'result': {}, 'retExtInfo': {}, 'time': 1741071656593}
2025-03-04 16:00:57,601 - services.trade_history_service - INFO - 기간별 조회: 2024-12-18 ~ 2024-12-25
2025-03-04 16:00:57,602 - services.trade_history_service - DEBUG - API 요청 파라미터: {'category': 'linear', 'symbol': 'BTCUSDT', 'startTime': '1734505255180', 'endTime': '1735110055180', 'limit': 100}
2025-03-04 16:00:57,720 - services.trade_history_service - DEBUG - API 응답: {'retCode': 10004, 'retMsg': 'error sign! origin_string[1741071657595yjHTlVOB6X6Man1Ah55000category=linear&symbol=BTCUSDT&startTime=1734505255180&endTime=1735110055180&limit=100&timestamp=1741071657595]', 'result': {}, 'retExtInfo': {}, 'time': 1741071657713}
2025-03-04 16:00:58,735 - services.trade_history_service - INFO - 기간별 조회: 2024-12-25 ~ 2025-01-01
2025-03-04 16:00:58,736 - services.trade_history_service - DEBUG - API 요청 파라미터: {'category': 'linear', 'symbol': 'BTCUSDT', 'startTime': '1735110055180', 'endTime': '1735714855180', 'limit': 100}
2025-03-04 16:00:58,874 - services.trade_history_service - DEBUG - API 응답: {'retCode': 10004, 'retMsg': 'error sign! origin_string[1741071658729yjHTlVOB6X6Man1Ah55000category=linear&symbol=BTCUSDT&startTime=1735110055180&endTime=1735714855180&limit=100&timestamp=1741071658729]', 'result': {}, 'retExtInfo': {}, 'time': 1741071658864}
2025-03-04 16:00:59,868 - services.trade_history_service - INFO - 기간별 조회: 2025-01-01 ~ 2025-01-08
2025-03-04 16:00:59,868 - services.trade_history_service - DEBUG - API 요청 파라미터: {'category': 'linear', 'symbol': 'BTCUSDT', 'startTime': '1735714855180', 'endTime': '1736319655180', 'limit': 100}
2025-03-04 16:00:59,994 - services.trade_history_service - DEBUG - API 응답: {'retCode': 10004, 'retMsg': 'error sign! origin_string[1741071659860yjHTlVOB6X6Man1Ah55000category=linear&symbol=BTCUSDT&startTime=1735714855180&endTime=1736319655180&limit=100&timestamp=1741071659860]', 'result': {}, 'retExtInfo': {}, 'time': 1741071659985}
2025-03-04 16:01:00,999 - services.trade_history_service - INFO - 기간별 조회: 2025-01-08 ~ 2025-01-15
2025-03-04 16:01:00,999 - services.trade_history_service - DEBUG - API 요청 파라미터: {'category': 'linear', 'symbol': 'BTCUSDT', 'startTime': '1736319655180', 'endTime': '1736924455180', 'limit': 100}
2025-03-04 16:01:01,121 - services.trade_history_service - DEBUG - API 응답: {'retCode': 10004, 'retMsg': 'error sign! origin_string[1741071660991yjHTlVOB6X6Man1Ah55000category=linear&symbol=BTCUSDT&startTime=1736319655180&endTime=1736924455180&limit=100&timestamp=1741071660991]', 'result': {}, 'retExtInfo': {}, 'time': 1741071661113}
2025-03-04 16:01:02,113 - services.trade_history_service - INFO - 기간별 조회: 2025-01-15 ~ 2025-01-22
2025-03-04 16:01:02,113 - services.trade_history_service - DEBUG - API 요청 파라미터: {'category': 'linear', 'symbol': 'BTCUSDT', 'startTime': '1736924455180', 'endTime': '1737529255180', 'limit': 100}
2025-03-04 16:01:02,217 - services.trade_history_service - DEBUG - API 응답: {'retCode': 10004, 'retMsg': 'error sign! origin_string[1741071662105yjHTlVOB6X6Man1Ah55000category=linear&symbol=BTCUSDT&startTime=1736924455180&endTime=1737529255180&limit=100&timestamp=1741071662105]', 'result': {}, 'retExtInfo': {}, 'time': 1741071662216}
2025-03-04 16:01:03,217 - services.trade_history_service - INFO - 기간별 조회: 2025-01-22 ~ 2025-01-29
2025-03-04 16:01:03,217 - services.trade_history_service - DEBUG - API 요청 파라미터: {'category': 'linear', 'symbol': 'BTCUSDT', 'startTime': '1737529255180', 'endTime': '1738134055180', 'limit': 100}
2025-03-04 16:01:03,320 - services.trade_history_service - DEBUG - API 응답: {'retCode': 10004, 'retMsg': 'error sign! origin_string[1741071663209yjHTlVOB6X6Man1Ah55000category=linear&symbol=BTCUSDT&startTime=1737529255180&endTime=1738134055180&limit=100&timestamp=1741071663209]', 'result': {}, 'retExtInfo': {}, 'time': 1741071663320}
2025-03-04 16:01:04,321 - services.trade_history_service - INFO - 기간별 조회: 2025-01-29 ~ 2025-02-05
2025-03-04 16:01:04,322 - services.trade_history_service - DEBUG - API 요청 파라미터: {'category': 'linear', 'symbol': 'BTCUSDT', 'startTime': '1738134055180', 'endTime': '1738738855180', 'limit': 100}
2025-03-04 16:01:04,440 - services.trade_history_service - DEBUG - API 응답: {'retCode': 10004, 'retMsg': 'error sign! origin_string[1741071664315yjHTlVOB6X6Man1Ah55000category=linear&symbol=BTCUSDT&startTime=1738134055180&endTime=1738738855180&limit=100&timestamp=1741071664315]', 'result': {}, 'retExtInfo': {}, 'time': 1741071664434}
2025-03-04 16:01:05,441 - services.trade_history_service - INFO - 기간별 조회: 2025-02-05 ~ 2025-02-12
2025-03-04 16:01:05,441 - services.trade_history_service - DEBUG - API 요청 파라미터: {'category': 'linear', 'symbol': 'BTCUSDT', 'startTime': '1738738855180', 'endTime': '1739343655180', 'limit': 100}
2025-03-04 16:01:05,549 - services.trade_history_service - DEBUG - API 응답: {'retCode': 10004, 'retMsg': 'error sign! origin_string[1741071665433yjHTlVOB6X6Man1Ah55000category=linear&symbol=BTCUSDT&startTime=1738738855180&endTime=1739343655180&limit=100&timestamp=1741071665433]', 'result': {}, 'retExtInfo': {}, 'time': 1741071665543}
2025-03-04 16:01:06,558 - services.trade_history_service - INFO - 기간별 조회: 2025-02-12 ~ 2025-02-19
2025-03-04 16:01:06,558 - services.trade_history_service - DEBUG - API 요청 파라미터: {'category': 'linear', 'symbol': 'BTCUSDT', 'startTime': '1739343655180', 'endTime': '1739948455180', 'limit': 100}
2025-03-04 16:01:06,671 - services.trade_history_service - DEBUG - API 응답: {'retCode': 10004, 'retMsg': 'error sign! origin_string[1741071666551yjHTlVOB6X6Man1Ah55000category=linear&symbol=BTCUSDT&startTime=1739343655180&endTime=1739948455180&limit=100&timestamp=1741071666551]', 'result': {}, 'retExtInfo': {}, 'time': 1741071666661}
2025-03-04 16:01:07,672 - services.trade_history_service - INFO - 기간별 조회: 2025-02-19 ~ 2025-02-26
2025-03-04 16:01:07,672 - services.trade_history_service - DEBUG - API 요청 파라미터: {'category': 'linear', 'symbol': 'BTCUSDT', 'startTime': '1739948455180', 'endTime': '1740553255180', 'limit': 100}
2025-03-04 16:01:07,790 - services.trade_history_service - DEBUG - API 응답: {'retCode': 10004, 'retMsg': 'error sign! origin_string[1741071667664yjHTlVOB6X6Man1Ah55000category=linear&symbol=BTCUSDT&startTime=1739948455180&endTime=1740553255180&limit=100&timestamp=1741071667664]', 'result': {}, 'retExtInfo': {}, 'time': 1741071667784}
2025-03-04 16:01:08,799 - services.trade_history_service - INFO - 기간별 조회: 2025-02-26 ~ 2025-03-04
2025-03-04 16:01:08,799 - services.trade_history_service - DEBUG - API 요청 파라미터: {'category': 'linear', 'symbol': 'BTCUSDT', 'startTime': '1740553255180', 'endTime': '1741071655180', 'limit': 100}
2025-03-04 16:01:08,916 - services.trade_history_service - DEBUG - API 응답: {'retCode': 10004, 'retMsg': 'error sign! origin_string[1741071668792yjHTlVOB6X6Man1Ah55000category=linear&symbol=BTCUSDT&startTime=1740553255180&endTime=1741071655180&limit=100&timestamp=1741071668792]', 'result': {}, 'retExtInfo': {}, 'time': 1741071668906}
2025-03-04 16:01:09,928 - telegram_bot.bot - INFO - Application 빌드 시작...
2025-03-04 16:01:10,305 - apscheduler.scheduler - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2025-03-04 16:01:10,310 - telegram_bot.bot - INFO - 핸들러 초기화 완료
2025-03-04 16:01:10,311 - telegram_bot.bot - INFO - 봇 초기화 완료, 시작 준비 중...
2025-03-04 16:01:10,311 - telegram_bot.bot - INFO - 봇 시작 시도...
2025-03-04 16:01:10,311 - telegram_bot.bot - INFO - === 봇 시작 시도 ===
2025-03-04 16:01:11,411 - apscheduler.scheduler - INFO - Scheduler started
2025-03-04 16:01:11,411 - telegram.ext.Application - INFO - Application started
2025-03-04 16:01:11,691 - telegram_bot.bot - INFO - 🤖 바이빗 트레이딩 봇이 시작되었습니다
